### ISSUE TITLE
Animated Blocks Not Animating

### ISSUE THREAD

**Issue by 8BitBunnie** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#100]
I've made an animation, installed GeckoLib API, and told the block to play the animation when placed, yet it still doesn't animate. This is occuring to all of my animated blocks and items.
The procedure that occurs when placed by
![image](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/114538991/473a50e6-3880-4cd8-8415-cae78c68f09a)
Ignore that for whatever reason the gif is at half speed, the animation is actually 1.13 seconds long. Animation 0 is just two keyframes of nothing.
![Pop Up Chest Open](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/114538991/94040ef2-861d-4498-a30a-ac7f6433fcae)
The animation not playing in-game. It instead places then waits 22.6 ticks and gets removed (Which is intended, but the lack of animation isn't.)
![In-Game](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/114538991/24bf367f-c34a-4de5-9f2a-a9e072d5fed2)

**Comment by NerdyPuzzle** [comment]
Your animation names are wrong
![Screenshot_2024-03-30-19-19-41-50_cbf47468f7ecfbd8ebcc46bf9cc626da.jpg](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/112079900/44fe437e-dcb0-4fed-8944-1bfb37faabf7)

**Comment by 8BitBunnie** [comment]
It doesn't seem like I can enter letters into the [play animation named (x) to the block at x y z] block though, only numbers

**Comment by NerdyPuzzle** [comment]
When you make the animation, rename the whole thing to 0 or 1, not just the last word.

**Comment by NerdyPuzzle** [comment]
Your animations are animation.popup.0 and 1, not 0 and 1.
