### ISSUE TITLE
Animated Armor "Chestplate tick event" not working!

### ISSUE THREAD

**Issue by TheRedstoneWolf** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#102]
I use MCreator 2023.4 and GeckoLib 5.4.3.

I wanted to use the "Chestplate tick event" to play different animations when the player does certain things. After several unsuccessful attempts I wanted to test if the event works at all, so I just sent a chat message:

Event trigger - triggered by external call
Send to chat: "Chestplate tick event update"

However, this message is not displayed in the chat, so I assume that the event is not working. I'm still new, so I might be doing it wrong, but all I want is that when the player stops touching the ground, the chestplate should play the animation "Unfold" and as soon as the player touches the ground again, the chestplate should play the animation "Fold". Can anyone help me? The problem above is probably a bug that should be fixed.

**Comment by NerdyPuzzle** [comment]
armor tick events are scrapped now
