### ISSUE TITLE
I can't play different animations on my Armor!

### ISSUE THREAD

**Issue by TheRedstoneWolf** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#103]
I use MCreator 2023.4 and Minecraft version 1.20.1.
Geckolib version 5.4.3

I have created three different animations for my Armor (all are "hold on last frame"). I have defined the main animation in the properties. With the help of a procedure I wanted to execute a certain animation depending on whether the player touches the ground or not. For testing I have sent a chat message behind the Geckolib play animation blocks. This also arrives, which means that the procedure is executed. However, the animations are not executed.
![Bild_2024-04-10_203058228](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/111454110/f3524ebb-0883-4bc6-aa57-8aa3be4f5c42)

**Comment by NerdyPuzzle** [comment]
Seems like the same issue as #89

**Comment by TheRedstoneWolf** [comment]
Ok, thanks but there are no answers for this issue yet so that doesn't really help me. The issue also has no labels.

**Comment by NerdyPuzzle** [comment]
I haven't had time to fix it yet.

**Comment by TheRedstoneWolf** [comment]
ok
