### ISSUE TITLE
[Feature] Walk animation speedup

### ISSUE THREAD

**Issue by Marianz222** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#105]
With the title, this is what I mean:

Imagine you have a mob that has a 3 block/second movement speed, and you make a walking animation for that mob, but then you give the mob "Speed III" for example, your animation will look slow and out of place, my suggestion was If it's even possible to add a way to trim the walk animation automatically depending on the speed of the mob, so the animation plays faster whenever the mob runs faster (I know there are sprint animations, but those can feel also out of place if the mob goes faster than intended). I think having this could be great, and maybe can be applied to other actions like fly or swimming animations being influenced by the fly_speed and swim_speed attributes and base values

**Comment by NerdyPuzzle** [comment]
You do that using molang queries in the animation. You can find supported queries in the geckolib GitHub wiki.
