### ISSUE TITLE
v.5.7 Entities Randomly Move Their Heads

### ISSUE THREAD

**Issue by gooseDes** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#111]
Entities randomly move their heads

MCretor v. 2024.1
Plugin v. 5.7
No other plugins installed!

https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/166229741/2d383d0c-a4d6-47e6-bbee-278623442c45

https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/166229741/1aa8053e-c8d0-4dc1-9e03-b8eea2212dae

**Comment by NerdyPuzzle** [comment]
Fixed
