### ISSUE TITLE
Animations stop when entities walk over soul sand.

### ISSUE THREAD

**Issue by LostZ0mbie** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#112]
I made a mob that spawns in the soul sand valley everything works fine but the moment it walks over soul sand it slide across with no animation I tried using the sneak animation but that didn't work. Is there a solution or is this a bug?

**Comment by NerdyPuzzle** [comment]
Your entity is probably just walking too slow to count as moving.
