### ISSUE TITLE
Missing generator/plugin features

### ISSUE THREAD

**Issue by pichugirl11** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#113]
I had version 2023.1 with geckolib 2023.1 but as soon as i updated to 2024.1 and replaced my geckolib 2023.1 with 2024.1 i was unable to boot up my old workspace with the new version i got an error and it wouldn't let me launch it
[mcreator_2024_05_26-8.log](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/files/15449233/mcreator_2024_05_26-8.log)

**Comment by NerdyPuzzle** [comment]
This is because mcreator thinks the plugin is a generator but since it doesn't have templates for any elements they come up as missing features. Go in the plugin zip and delete the forge-1.19.2 folder.
