### ISSUE TITLE
Looping Animations cannot be stopped.

### ISSUE THREAD

**Issue by NovaManGood2110** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#114]
I'd like to be able to have an item hold on different animations than idle.

Maybe I'm doing this wrong I don't know but if I play a looping or holding animation the item is permanently stuck like that and I cannot make a procedure play a new animation or stop the animation back to the default idle animation.

**Comment by Yukinao520** [comment]
Maybe it doesn't support looping animations per se, only idle animations that automatically loop by default

**Comment by StephenJBanks** [comment]
Seconded
