### ISSUE TITLE
Error generating itemAnimationFactory

### ISSUE THREAD

**Issue by Dioooooooos** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#115]
I use MCreator 2024.1 and GeckoLib 5.7.1,Forge v1.19.2
The following is the error message
[C:\Users\KuJoSheepTaro\MCreatorWorkspaces\test\src\main\java\net\mcreator\test\init\ItemAnimationFactory.java:34](file:///C:/Users/MCreatorWorkspaces/test/src/main/java/net/mcreator/test/init/ItemAnimationFactory.java:34): error: cannot find symbol 
        if (event.phase == TickEvent.Phase.START && (mainhandItem.getItem() instanceof GeoItem || offhandItem.getItem() instanceof GeoItem)) { 
                                                                                       ^ 
  symbol:   class GeoItem 
  location: class ItemAnimationFactory 
[C:\Users/MCreatorWorkspaces\test\src\main\java\net\mcreator\test\init\ItemAnimationFactory.java:34](file:///C:/Users/KuJoSheepTaro/MCreatorWorkspaces/test/src/main/java/net/mcreator/test/init/ItemAnimationFactory.java:34): error: cannot find symbol 
        if (event.phase == TickEvent.Phase.START && (mainhandItem.getItem() instanceof GeoItem || offhandItem.getItem() instanceof GeoItem)) { 
                                                                                                                                   ^ 
  symbol:   class GeoItem 
  location: class ItemAnimationFactory

**Comment by Dioooooooos** [comment]
and, in animation_sync_factory.java, it seems that you added an extra} at the end of the code

**Comment by NerdyPuzzle** [comment]
You probably have an outdated version of the plugin still loaded, make sure you only have the latest version in your plugins folder

**Comment by NerdyPuzzle** [comment]
1.19.2 is no longer supported and will be removed from the plugin next update
