### ISSUE TITLE
Old Version of Plugin Breaks Between 1.18.2 and 1.19.2 for MCreator 2022.3

### ISSUE THREAD

**Issue by S33R-OF-PYR3** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#117]
I've been using an older version of this Plugin in MCreator 2022.3 and it worked great for my 1.18.2 mod. However, after updating the mod into 1.19.2, the entities have broken. Each entity throws about 11 `error: cannot find symbol` messages, and no amount of regenerating the code has resolved it. The plugin is still loaded according to MCreator, and the API is still checked.

![4](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/117496140/4e0153c1-5ab1-4615-9d48-25c0af41f9c5)

![3](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/117496140/e59be580-a6bf-4f26-8d74-8d0347195b88)

I've tried using the [newer](https://mcreator.net/plugin/91484/nerdys-geckolib-plugin-forge-1182-1192) version of the plugin as they also have folders inside labelled 1.18.2 and 1.19.2, but they don't show up as an installed plugin, nor is there a tab to upload the GeckoLib models (I have Java Plugins installed).

I'd really appreciate help in figuring out why the plugin is having issues. I would link where it's downloaded from, but it seems to have been removed from MCreator. The [tutorial](https://mcreator.net/forum/91485/tutorial-how-use-nerdys-geckolib-plugin) I used with the plugin is still available though.

**Comment by NerdyPuzzle** [comment]
2023.3 was left behind a long time ago and no new versions of my plugins support it.

**Comment by S33R-OF-PYR3** [comment]
Wonderful thanks. It still works for 1.18.2, so I'll keep messing with it.
