### ISSUE TITLE
Chance of not activating when in-game animation is playing

### ISSUE THREAD

**Issue by Yukinao520** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#119]
The animation itself is fine, but sometimes the animation may not be activated, either because it does not play or because it may not play until the next command is executed.

I swear my animation playback flow is not wrong, maybe it's because of some issues with the animations supported by the API itself, maybe it would work better if I could add a flow to force high priority playback with a bar

**Comment by NerdyPuzzle** [comment]
Are you using google translate? Because it's hard to understand what you're trying to say.

**Comment by Yukinao520** [comment]
Yes, Google Translate doesn't quite match what I need to say, about which I apologize, I can explain with an example:
Let's say I need to create a pistol that has 8 bullets, it doesn't have a very high rate of fire, each time it fires it plays the firing animation in full, but when I fire continuously there is a probability that suddenly the animation doesn't play but when the next shot is fired the animation playback goes back to normal, this occurs at random and has nothing to do with the process I'm creating.

**Comment by Yukinao520** [comment]
Maybe it has something to do with how high the animation is prioritized for playback? My Mcreaotr version is 2024.1.18518 and geckolib plugin is 5.7.1

**Comment by NerdyPuzzle** [comment]
You need to first stop the animation playing with the procedure block that does that. Then, you use the wait procedure block to wait 1 tick and play the animation.

**Comment by Yukinao520** [comment]
Ok,I'll try this.

**Comment by Yukinao520** [comment]
![test](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/98874801/4a4fce09-5ff2-4e1c-94d2-a8875591771c)

**Comment by Yukinao520** [comment]
I did what you said, but sometimes I still have the above problem
