### ISSUE TITLE
Animated Entity Shrunk (2023.1)

### ISSUE THREAD

**Issue by MichaelMichelle2** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#12]
I was making a creature that is the size of the elder guardian on block bench (using the elder guardian as a base) but when uploading it as an animated Entity, it appears to be the size or a normal guardian somehow.

**Comment by NerdyPuzzle** [comment]
This is not an issue if you are not using an extremely outdated version, plus new versions offer a parameter that can control the size of the model.

**Comment by MichaelMichelle2** [comment]
I am using all the new versions, what parameter changes the size? I don't see anything in MCreator? Unless you mean Blockbench

**Comment by NerdyPuzzle** [comment]
In the animated entity element.
