### ISSUE TITLE
Bug with inverse kinematics while using 2 locators on a animation.

### ISSUE THREAD

**Issue by Arthur508** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#120]
I am having a problem trying to use inverse kinematics with two locators on the same folder to make a more realistic tentacle movement. In Blockbench, the animation is perfect, but in the game itself, the animation gets glitchy. I suspect this happens because of the use of the two locators, since I never had this problem before while using only one.

Here is some footage of the problem:

The animation on Blockbench
https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/173959357/aaa265e8-2858-4a35-91cc-20f268c283bd

The animation on the game
https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/173959357/3fb6d02a-1c8b-4701-963f-bf8e7317e39f

**Comment by NerdyPuzzle** [comment]
This is likely not caused by the plugin but by geckolib not supporting whatever this is you're talking about.
