### ISSUE TITLE
Sneak and Sprint animations unresponsive to NBT

### ISSUE THREAD

**Issue by StephenJBanks** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#122]
Sneak and Sprint animations can't be activated if you control the sneak/sprint with NBT tags (even if server-synced), in my version (5.6.6). This severely limits the power of the plugin to be able to toggle those animations with NBT changes, especially since the regular procedure-based blocks don't work in looping formats in the way that  I need them to.

**Comment by NerdyPuzzle** [comment]
Sneak and sprint need to be set on the client too. Use synced data instead of nbts.

**Comment by StephenJBanks** [comment]
Thanks for the reply, I've narrowed the issue down more. It does work with server-synced data, which I've been using, but it doesn't work with checking whether the entity is targeting another one for attack (I do this with "IF (get entity (event/target entity) is targeting for attack) is the same entity as NO ENTITY, (else...). Same story for triggering crouching etc from the entity setting its target global variable.
This prevents me from being able to create sequences that only activate for mobs that are aggressive. Hopefully some way around it.
