### ISSUE TITLE
[2024.2] Animated entities' code is broken

### ISSUE THREAD

**Issue by VikkiVuk** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#123]
Hi, so I recently updated my project from 2024.1 to 2024.2 and when I did an element failed to compile and that element was an AnimatedEntity, so I dug a bit as to why and in the autogenerated code i saw this:
![image](https://github.com/user-attachments/assets/91da92a8-b804-422b-aac3-5a227aa66f97)
I somehow narrowed it down and found out that that specific code slice happens only if the mob natural spawning type is set to "creature", setting it to "monster" or any other type seems to fix it.

**Comment by NerdyPuzzle** [comment]
this is only on 1.20.6 right?

**Comment by VikkiVuk** [comment]
Yes, the workspace I have issues on is NF 1.20.6, I have tested it in F 1.20.1 and it generates the code just fine there.
