### ISSUE TITLE
Conflicting Plugin

### ISSUE THREAD

**Issue by RipleyMods** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#124]
I'm sure you've gotten a few comments about this but I figured I would ask again here to get a more concrete resolve. I use MCreator 2024.1 and as of the most recent 2024.1 update geckolib causes mcreator to break when attempting to use the popular 1.19 forge generators 

(https://mcreator.net/plugin/105663/minecraft-forge-1194-java-editiondatapack-generator)

 I know those plugins are not your responsibility, but any idea what causes this? When I attempt to convert a workspace with Geckolib elements, it says:

 "error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;" 

for every single element in my mod. If this is just a case of two conflicting codes from two separate plugin authors, that's an unfortunate reality, but if it's something that could be fixed that would be great. The generators have worked flawlessly with geckolib in the past, not sure what changed with 2024.1

Appreciate the time!

![Screenshot 2024-07-21 034708](https://github.com/user-attachments/assets/3d2179d5-1c48-4d52-a884-7e93bc28ece0)

**Comment by NerdyPuzzle** [comment]
I do not support 3rd party generators.
