### ISSUE TITLE
[2023.3 Version] Animations that are suppose to play during GUI interaction isn't working.

### ISSUE THREAD

**Issue by pantsguyapp** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#126]
I am making a custom chest using Animated Block feature of Geckolib, and I want the block to have 3 distinct animations 
1 - Opening
2 - Lid stay open during usage
3 - Closing

I set that the animation in the Open GUI procedure is 1, During GUI open tick is 2 and After GUI interaction is 3, and so far only Open and After GUI has proved to be working, only the "2" animation in During is not possible to play, I have tried everything in my power to make the chest to play its correct animations, and nothing worked, and yes, I have increased the Block procedure animations number in Visual

**Comment by pantsguyapp** [comment]
Also I have tried making the Opening animation to extend super long with the longing duration is the lid opening position and the Closing GUI procedure to have the game run Stop any Animation Procedure for Block first then play the closing animation but it also DOESN'T WORK. Help I have wasted 6 hours on this damn thing.

**Comment by pantsguyapp** [comment]
So you're saying the animation refuses to playing during GUI tick is intended? With your plan you have doomed those that want to make a chest for their mod, mcreator hasnt have a mod that add in custom chests for very long now, give us the animation playing during GUI tick at the least, so we can have chest lid that stay open during usage.

**Comment by NerdyPuzzle** [comment]
It should very much be possible to make chest-like blocks in the latest version. 2023.3? I really don't remember what the state of the plugin was like back then.

**Comment by pantsguyapp** [comment]
For chests, you would only see the animation as you are in the gui, so is it that you will only need to put in the animation block procedure like what I did above do you think?
