### ISSUE TITLE
Unsupported geometry crash on startup.

### ISSUE THREAD

**Issue by Kosmo-Pixc** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#128]
I've tried redoing the models, redoing the animations. I've also tried your tool to fix animations but it wouldn't open no matter what, even when opening as administrator. I really don't know what to do 
https://pastebin.com/GvaXRCdA

**Comment by NerdyPuzzle** [comment]
Are you sure that's even a geckolib model? Geckolib format models contain that parameter. Just delete the model from the workspace, the plugin is not at fault.
