### ISSUE TITLE
[Feature Request] - Get position of a especific bone.

### ISSUE THREAD

**Issue by Gabriel-H-R** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#129]
It would be cool if you added a procedure that allows you to obtain the xyz coordinates of a specific bone. This way, we could spawn particles as special effects coming out of a specific part of a creature (Like a flamethrower coming out of a dragon's head) even if the head is animated.

**Comment by NerdyPuzzle** [comment]
The values would be clientside only so that's not going to be very useful, plus you need access to the model code to do that so it can't be used in procedures.
