### ISSUE TITLE
Crash with Animated Item

### ISSUE THREAD

**Issue by Potato644** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#130]
Whenever I start the game, it gets to Mojang studios screen, then shows "▯▯▯▯▯" on a dirt screen and crashes. I've only found one other person with my [problem](https://mcreator.net/forum/93633/cannot-deserialize-formatversion)
The crash report:
[crash-2024-07-30_12.50.41-client.txt](https://github.com/user-attachments/files/16431868/crash-2024-07-30_12.50.41-client.txt)

**Comment by NerdyPuzzle** [comment]
This is a case of a broken model and nothing to do with the plugin.
