### ISSUE TITLE
Code not compiling [Neoforge 1.20.6 (Latest geckolib plugin, 5.8.3)]

### ISSUE THREAD

**Issue by ThePrimeDev** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#133]
Hello. I get this error uppon compiling: 
![image](https://github.com/user-attachments/assets/7ad73645-e925-4188-b2aa-a6eb8ba7472d)
`> Task :compileJava 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\display\CursedEnchantingTableDisplayItem.java:3](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/display/CursedEnchantingTableDisplayItem.java:3): error: package software.bernie.geckolib.util does not exist 
import software.bernie.geckolib.util.GeckoLibUtil; 
                                    ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\display\CursedEnchantingTableDisplayItem.java:4](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/display/CursedEnchantingTableDisplayItem.java:4): error: package software.bernie.geckolib.animation does not exist 
import software.bernie.geckolib.animation.PlayState; 
                                         ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\display\CursedEnchantingTableDisplayItem.java:5](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/display/CursedEnchantingTableDisplayItem.java:5): error: package software.bernie.geckolib.animation does not exist 
import software.bernie.geckolib.animation.AnimationState; 
                                         ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\display\CursedEnchantingTableDisplayItem.java:6](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/display/CursedEnchantingTableDisplayItem.java:6): error: package software.bernie.geckolib.animation does not exist 
import software.bernie.geckolib.animation.AnimationController; 
                                         ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\display\CursedEnchantingTableDisplayItem.java:7](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/display/CursedEnchantingTableDisplayItem.java:7): error: package software.bernie.geckolib.animation does not exist 
import software.bernie.geckolib.animation.AnimatableManager; 
                                         ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\display\CursedEnchantingTableDisplayItem.java:8](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/display/CursedEnchantingTableDisplayItem.java:8): error: package software.bernie.geckolib.animatable.instance does not exist 
import software.bernie.geckolib.animatable.instance.AnimatableInstanceCache; 
                                                   ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\display\CursedEnchantingTableDisplayItem.java:9](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/display/CursedEnchantingTableDisplayItem.java:9): error: package software.bernie.geckolib.animatable does not exist 
import software.bernie.geckolib.animatable.GeoItem; 
                                          ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\display\CursedEnchantingTableDisplayItem.java:22](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/display/CursedEnchantingTableDisplayItem.java:22): error: cannot find symbol 
public class CursedEnchantingTableDisplayItem extends BlockItem implements GeoItem { 
                                                                           ^ 
  symbol: class GeoItem 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\display\CursedEnchantingTableDisplayItem.java:23](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/display/CursedEnchantingTableDisplayItem.java:23): error: cannot find symbol 
    private final AnimatableInstanceCache cache = GeckoLibUtil.createInstanceCache(this); 
                  ^ 
  symbol:   class AnimatableInstanceCache 
  location: class CursedEnchantingTableDisplayItem 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\display\CursedEnchantingTableDisplayItem.java:29](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/display/CursedEnchantingTableDisplayItem.java:29): error: cannot find symbol 
    private PlayState predicate(AnimationState event) { 
                                ^ 
  symbol:   class AnimationState 
  location: class CursedEnchantingTableDisplayItem 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\display\CursedEnchantingTableDisplayItem.java:29](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/display/CursedEnchantingTableDisplayItem.java:29): error: cannot find symbol 
    private PlayState predicate(AnimationState event) { 
            ^ 
  symbol:   class PlayState 
  location: class CursedEnchantingTableDisplayItem 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\display\CursedEnchantingTableDisplayItem.java:47](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/display/CursedEnchantingTableDisplayItem.java:47): error: package AnimatableManager does not exist 
    public void registerControllers(AnimatableManager.ControllerRegistrar data) { 
                                                     ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\display\CursedEnchantingTableDisplayItem.java:52](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/display/CursedEnchantingTableDisplayItem.java:52): error: cannot find symbol 
    public AnimatableInstanceCache getAnimatableInstanceCache() { 
           ^ 
  symbol:   class AnimatableInstanceCache 
  location: class CursedEnchantingTableDisplayItem 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\entity\CursedEnchantingTableTileEntity.java:3](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/entity/CursedEnchantingTableTileEntity.java:3): error: package software.bernie.geckolib.util does not exist 
import software.bernie.geckolib.util.GeckoLibUtil; 
                                    ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\entity\CursedEnchantingTableTileEntity.java:4](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/entity/CursedEnchantingTableTileEntity.java:4): error: package software.bernie.geckolib.animation does not exist 
import software.bernie.geckolib.animation.RawAnimation; 
                                         ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\entity\CursedEnchantingTableTileEntity.java:5](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/entity/CursedEnchantingTableTileEntity.java:5): error: package software.bernie.geckolib.animation does not exist 
import software.bernie.geckolib.animation.PlayState; 
                                         ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\entity\CursedEnchantingTableTileEntity.java:6](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/entity/CursedEnchantingTableTileEntity.java:6): error: package software.bernie.geckolib.animation does not exist 
import software.bernie.geckolib.animation.AnimationState; 
                                         ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\entity\CursedEnchantingTableTileEntity.java:7](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/entity/CursedEnchantingTableTileEntity.java:7): error: package software.bernie.geckolib.animation does not exist 
import software.bernie.geckolib.animation.AnimationController; 
                                         ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\entity\CursedEnchantingTableTileEntity.java:8](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/entity/CursedEnchantingTableTileEntity.java:8): error: package software.bernie.geckolib.animation does not exist 
import software.bernie.geckolib.animation.AnimatableManager; 
                                         ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\entity\CursedEnchantingTableTileEntity.java:9](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/entity/CursedEnchantingTableTileEntity.java:9): error: package software.bernie.geckolib.animatable.instance does not exist 
import software.bernie.geckolib.animatable.instance.AnimatableInstanceCache; 
                                                   ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\entity\CursedEnchantingTableTileEntity.java:10](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/entity/CursedEnchantingTableTileEntity.java:10): error: package software.bernie.geckolib.animatable does not exist 
import software.bernie.geckolib.animatable.GeoBlockEntity; 
                                          ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\entity\CursedEnchantingTableTileEntity.java:38](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/entity/CursedEnchantingTableTileEntity.java:38): error: cannot find symbol 
public class CursedEnchantingTableTileEntity extends RandomizableContainerBlockEntity implements GeoBlockEntity, WorldlyContainer { 
                                                                                                 ^ 
  symbol: class GeoBlockEntity 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\entity\CursedEnchantingTableTileEntity.java:39](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/entity/CursedEnchantingTableTileEntity.java:39): error: cannot find symbol 
    private final AnimatableInstanceCache cache = GeckoLibUtil.createInstanceCache(this); 
                  ^ 
  symbol:   class AnimatableInstanceCache 
  location: class CursedEnchantingTableTileEntity 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\entity\CursedEnchantingTableTileEntity.java:47](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/entity/CursedEnchantingTableTileEntity.java:47): error: cannot find symbol 
    private PlayState predicate(AnimationState event) { 
                                ^ 
  symbol:   class AnimationState 
  location: class CursedEnchantingTableTileEntity 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\entity\CursedEnchantingTableTileEntity.java:47](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/entity/CursedEnchantingTableTileEntity.java:47): error: cannot find symbol 
    private PlayState predicate(AnimationState event) { 
            ^ 
  symbol:   class PlayState 
  location: class CursedEnchantingTableTileEntity 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\entity\CursedEnchantingTableTileEntity.java:57](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/entity/CursedEnchantingTableTileEntity.java:57): error: cannot find symbol 
    private PlayState procedurePredicate(AnimationState event) { 
                                         ^ 
  symbol:   class AnimationState 
  location: class CursedEnchantingTableTileEntity 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\entity\CursedEnchantingTableTileEntity.java:57](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/entity/CursedEnchantingTableTileEntity.java:57): error: cannot find symbol 
    private PlayState procedurePredicate(AnimationState event) { 
            ^ 
  symbol:   class PlayState 
  location: class CursedEnchantingTableTileEntity 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\entity\CursedEnchantingTableTileEntity.java:77](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/entity/CursedEnchantingTableTileEntity.java:77): error: package AnimatableManager does not exist 
    public void registerControllers(AnimatableManager.ControllerRegistrar data) { 
                                                     ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\entity\CursedEnchantingTableTileEntity.java:83](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/entity/CursedEnchantingTableTileEntity.java:83): error: cannot find symbol 
    public AnimatableInstanceCache getAnimatableInstanceCache() { 
           ^ 
  symbol:   class AnimatableInstanceCache 
  location: class CursedEnchantingTableTileEntity 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\model\CursedEnchantingTableBlockModel.java:3](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/model/CursedEnchantingTableBlockModel.java:3): error: package software.bernie.geckolib.model does not exist 
import software.bernie.geckolib.model.GeoModel; 
                                     ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\model\CursedEnchantingTableBlockModel.java:9](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/model/CursedEnchantingTableBlockModel.java:9): error: cannot find symbol 
public class CursedEnchantingTableBlockModel extends GeoModel<CursedEnchantingTableTileEntity> { 
                                                     ^ 
  symbol: class GeoModel 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\model\CursedEnchantingTableDisplayModel.java:3](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/model/CursedEnchantingTableDisplayModel.java:3): error: package software.bernie.geckolib.model does not exist 
import software.bernie.geckolib.model.GeoModel; 
                                     ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\model\CursedEnchantingTableDisplayModel.java:9](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/model/CursedEnchantingTableDisplayModel.java:9): error: cannot find symbol 
public class CursedEnchantingTableDisplayModel extends GeoModel<CursedEnchantingTableDisplayItem> { 
                                                       ^ 
  symbol: class GeoModel 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\renderer\CursedEnchantingTableDisplayItemRenderer.java:3](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/renderer/CursedEnchantingTableDisplayItemRenderer.java:3): error: package software.bernie.geckolib.renderer does not exist 
import software.bernie.geckolib.renderer.GeoItemRenderer; 
                                        ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\renderer\CursedEnchantingTableDisplayItemRenderer.java:12](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/renderer/CursedEnchantingTableDisplayItemRenderer.java:12): error: cannot find symbol 
public class CursedEnchantingTableDisplayItemRenderer extends GeoItemRenderer<CursedEnchantingTableDisplayItem> { 
                                                              ^ 
  symbol: class GeoItemRenderer 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\renderer\CursedEnchantingTableTileRenderer.java:3](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/renderer/CursedEnchantingTableTileRenderer.java:3): error: package software.bernie.geckolib.renderer does not exist 
import software.bernie.geckolib.renderer.GeoBlockRenderer; 
                                        ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\renderer\CursedEnchantingTableTileRenderer.java:12](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/renderer/CursedEnchantingTableTileRenderer.java:12): error: cannot find symbol 
public class CursedEnchantingTableTileRenderer extends GeoBlockRenderer<CursedEnchantingTableTileEntity> { 
                                                       ^ 
  symbol: class GeoBlockRenderer 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\display\CursedEnchantingTableDisplayItem.java:23](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/display/CursedEnchantingTableDisplayItem.java:23): error: cannot find symbol 
    private final AnimatableInstanceCache cache = GeckoLibUtil.createInstanceCache(this); 
                                                  ^ 
  symbol:   variable GeckoLibUtil 
  location: class CursedEnchantingTableDisplayItem 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\display\CursedEnchantingTableDisplayItem.java:30](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/display/CursedEnchantingTableDisplayItem.java:30): error: cannot find symbol 
        return PlayState.CONTINUE; 
               ^ 
  symbol:   variable PlayState 
  location: class CursedEnchantingTableDisplayItem 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\display\CursedEnchantingTableDisplayItem.java:37](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/display/CursedEnchantingTableDisplayItem.java:37): error: incompatible types: CursedEnchantingTableDisplayItemRenderer cannot be converted to BlockEntityWithoutLevelRenderer 
            private final BlockEntityWithoutLevelRenderer renderer = new CursedEnchantingTableDisplayItemRenderer(); 
                                                                     ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\display\CursedEnchantingTableDisplayItem.java:46](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/display/CursedEnchantingTableDisplayItem.java:46): error: method does not override or implement a method from a supertype 
    @Override 
    ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\display\CursedEnchantingTableDisplayItem.java:48](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/display/CursedEnchantingTableDisplayItem.java:48): error: cannot find symbol 
        data.add(new AnimationController(this, "controller", 0, this::predicate)); 
                     ^ 
  symbol:   class AnimationController 
  location: class CursedEnchantingTableDisplayItem 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\display\CursedEnchantingTableDisplayItem.java:51](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/display/CursedEnchantingTableDisplayItem.java:51): error: method does not override or implement a method from a supertype 
    @Override 
    ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\entity\CursedEnchantingTableTileEntity.java:39](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/entity/CursedEnchantingTableTileEntity.java:39): error: cannot find symbol 
    private final AnimatableInstanceCache cache = GeckoLibUtil.createInstanceCache(this); 
                                                  ^ 
  symbol:   variable GeckoLibUtil 
  location: class CursedEnchantingTableTileEntity 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\entity\CursedEnchantingTableTileEntity.java:50](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/entity/CursedEnchantingTableTileEntity.java:50): error: cannot find symbol 
            return event.setAndContinue(RawAnimation.begin().thenLoop(animationprocedure)); 
                                        ^ 
  symbol:   variable RawAnimation 
  location: class CursedEnchantingTableTileEntity 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\entity\CursedEnchantingTableTileEntity.java:52](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/entity/CursedEnchantingTableTileEntity.java:52): error: cannot find symbol 
        return PlayState.STOP; 
               ^ 
  symbol:   variable PlayState 
  location: class CursedEnchantingTableTileEntity 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\entity\CursedEnchantingTableTileEntity.java:59](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/entity/CursedEnchantingTableTileEntity.java:59): error: package AnimationController does not exist 
        if (!animationprocedure.equals("0") && event.getController().getAnimationState() == AnimationController.State.STOPPED || (!animationprocedure.equals(prevAnim) && !animationprocedure.equals("0"))) { 
                                                                                                               ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\entity\CursedEnchantingTableTileEntity.java:62](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/entity/CursedEnchantingTableTileEntity.java:62): error: cannot find symbol 
            event.getController().setAnimation(RawAnimation.begin().thenPlay(animationprocedure)); 
                                               ^ 
  symbol:   variable RawAnimation 
  location: class CursedEnchantingTableTileEntity 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\entity\CursedEnchantingTableTileEntity.java:63](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/entity/CursedEnchantingTableTileEntity.java:63): error: package AnimationController does not exist 
            if (event.getController().getAnimationState() == AnimationController.State.STOPPED) { 
                                                                                ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\entity\CursedEnchantingTableTileEntity.java:70](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/entity/CursedEnchantingTableTileEntity.java:70): error: cannot find symbol 
            return PlayState.STOP; 
                   ^ 
  symbol:   variable PlayState 
  location: class CursedEnchantingTableTileEntity 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\entity\CursedEnchantingTableTileEntity.java:73](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/entity/CursedEnchantingTableTileEntity.java:73): error: cannot find symbol 
        return PlayState.CONTINUE; 
               ^ 
  symbol:   variable PlayState 
  location: class CursedEnchantingTableTileEntity 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\entity\CursedEnchantingTableTileEntity.java:76](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/entity/CursedEnchantingTableTileEntity.java:76): error: method does not override or implement a method from a supertype 
    @Override 
    ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\entity\CursedEnchantingTableTileEntity.java:78](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/entity/CursedEnchantingTableTileEntity.java:78): error: cannot find symbol 
        data.add(new AnimationController<CursedEnchantingTableTileEntity>(this, "controller", 0, this::predicate)); 
                     ^ 
  symbol:   class AnimationController 
  location: class CursedEnchantingTableTileEntity 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\entity\CursedEnchantingTableTileEntity.java:79](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/entity/CursedEnchantingTableTileEntity.java:79): error: cannot find symbol 
        data.add(new AnimationController<CursedEnchantingTableTileEntity>(this, "procedurecontroller", 0, this::procedurePredicate)); 
                     ^ 
  symbol:   class AnimationController 
  location: class CursedEnchantingTableTileEntity 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\entity\CursedEnchantingTableTileEntity.java:82](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/entity/CursedEnchantingTableTileEntity.java:82): error: method does not override or implement a method from a supertype 
    @Override 
    ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\listener\ClientListener.java:21](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/listener/ClientListener.java:21): error: incompatible types: cannot infer type-variable(s) T 
        event.registerBlockEntityRenderer((BlockEntityType<CursedEnchantingTableTileEntity>) TridentmodModBlockEntities.CURSED_ENCHANTING_TABLE.get(), context -> new CursedEnchantingTableTileRenderer()); 
                                         ^ 
    (argument mismatch; bad return type in lambda expression 
      CursedEnchantingTableTileRenderer cannot be converted to BlockEntityRenderer<T>) 
  where T is a type-variable: 
    T extends BlockEntity declared in method <T>registerBlockEntityRenderer(BlockEntityType<? extends T>,BlockEntityRendererProvider<T>) 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\model\CursedEnchantingTableBlockModel.java:10](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/model/CursedEnchantingTableBlockModel.java:10): error: method does not override or implement a method from a supertype 
    @Override 
    ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\model\CursedEnchantingTableBlockModel.java:15](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/model/CursedEnchantingTableBlockModel.java:15): error: method does not override or implement a method from a supertype 
    @Override 
    ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\model\CursedEnchantingTableBlockModel.java:20](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/model/CursedEnchantingTableBlockModel.java:20): error: method does not override or implement a method from a supertype 
    @Override 
    ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\model\CursedEnchantingTableDisplayModel.java:10](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/model/CursedEnchantingTableDisplayModel.java:10): error: method does not override or implement a method from a supertype 
    @Override 
    ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\model\CursedEnchantingTableDisplayModel.java:15](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/model/CursedEnchantingTableDisplayModel.java:15): error: method does not override or implement a method from a supertype 
    @Override 
    ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\model\CursedEnchantingTableDisplayModel.java:20](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/model/CursedEnchantingTableDisplayModel.java:20): error: method does not override or implement a method from a supertype 
    @Override 
    ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\renderer\CursedEnchantingTableDisplayItemRenderer.java:17](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/renderer/CursedEnchantingTableDisplayItemRenderer.java:17): error: method does not override or implement a method from a supertype 
    @Override 
    ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\renderer\CursedEnchantingTableDisplayItemRenderer.java:19](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/renderer/CursedEnchantingTableDisplayItemRenderer.java:19): error: cannot find symbol 
        return RenderType.entityTranslucent(getTextureLocation(animatable)); 
                                            ^ 
  symbol:   method getTextureLocation(CursedEnchantingTableDisplayItem) 
  location: class CursedEnchantingTableDisplayItemRenderer 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\renderer\CursedEnchantingTableTileRenderer.java:17](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/renderer/CursedEnchantingTableTileRenderer.java:17): error: method does not override or implement a method from a supertype 
    @Override 
    ^ 
[C:\Users\Jerryyy\MCreatorWorkspaces\tridentmod\src\main\java\net\voltary\tridentmod\block\renderer\CursedEnchantingTableTileRenderer.java:19](file:///C:/Users/Jerryyy/MCreatorWorkspaces/tridentmod/src/main/java/net/voltary/tridentmod/block/renderer/CursedEnchantingTableTileRenderer.java:19): error: cannot find symbol 
        return RenderType.entityTranslucent(getTextureLocation(animatable)); 
                                            ^ 
  symbol:   method getTextureLocation(CursedEnchantingTableTileEntity) 
  location: class CursedEnchantingTableTileRenderer 
66 errors`

I think it can't import the geckolib mod or smth like that. I don't know what can I do with it. (Yes, geckolib is enabled in the workspace settings)

**Comment by NerdyPuzzle** [comment]
This is an issue with gradle not the plugin.

**Comment by ThePrimeDev** [comment]
> This is an issue with gradle not the plugin.

Ideas how to fix it? I only have this error with geckolib animated things, so...

**Comment by NerdyPuzzle** [comment]
Clear gradle caches and folder
