### ISSUE TITLE
Need API fix for plugin

### ISSUE THREAD

**Issue by mirconchik** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#135]
Yo, I decided to rework ur plugin on 2023.1 for MCreator. I only have an issue with an API, cause it didn't shown after I loaded plugin in MCreator and created a project for 1.16.5. This is a completed version with 1.16.5 version by me, just need to fix API problem. Hope u will help
[Nerdys_Geckolib_Plugin_1_16_5.zip](https://github.com/user-attachments/files/16636638/Nerdys_Geckolib_Plugin_1_16_5.zip)

**Comment by NerdyPuzzle** [comment]
I do not provide support for outdated versions, this issue tracker is only for the latest version of the plugin.
