### ISSUE TITLE
Opened up Mcreator to this

### ISSUE THREAD

**Issue by ArchieBarkstar** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#137]
![image](https://github.com/user-attachments/assets/0fca938d-62b9-49aa-9e25-9b963ea457e2)

Basically, after downloading the new version of Geckolib, I ended up having these errors in Mcreator. On top of that, I have also noticed it takes up an unnaturally high amount of memory when trying to open my Geckolib-animated mobs, and I can't even open them to begin with, causing massive amounts of lag.
![image](https://github.com/user-attachments/assets/f64b53e0-2dc8-441e-a13f-8add3f8500a3)
![image](https://github.com/user-attachments/assets/49294ba4-ad13-494a-890a-9312dc4c9d34)
I can't click for the next page, and it is stuck here.

All I have is the v5.7.1 and v5.8.4 versions of Geckolib, and I have the 2024.2 port of Mcreator.

**Comment by ArchieBarkstar** [comment]
I tried uninstalling Mcreator and downloading it again, but that didn't work.
At this point, I have no idea what it causing all of this.

**Comment by NerdyPuzzle** [comment]
You have 2 versions loaded at the same time?

**Comment by ArchieBarkstar** [comment]
I have had the plugin set on 2 different versions of the plugin, and i had the same error

**Comment by ArchieBarkstar** [comment]
nvm it works now--

idk how, but it works now--

**Comment by ArchieBarkstar** [comment]
im sorry for being so clumsy about this, Nerdy; i am just a lil bit of a klutz--
