### ISSUE TITLE
Step Speed in Animated entity so step sounds can line up with the mob

### ISSUE THREAD

**Issue by Dashy22** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#138]
It would be a number you can change to adjust how quickly or slowly the entitys step sound plays
So if you have a big entity that walks slowly but moves fast then you lower it
but if you have like a centipede than you would increase it by alot.

Maybe it could be a multiplier or interval.

**Comment by NerdyPuzzle** [comment]
There is no such thing.
