### ISSUE TITLE
Disable Collisions Button doesn't Disable Collisions

### ISSUE THREAD

**Issue by Dashy22** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#139]
I clicked disable collisions on my mob and it's still headbutting into walls and stopping on them like a dork.
He clearly still has collisions, it's also a flying mob.

**Comment by NerdyPuzzle** [comment]
It stops collisions with entities, not blocks.

**Comment by Dashy22** [comment]
than it seems pretty useless but thanks
