### ISSUE TITLE
Crash: Rendering item

### ISSUE THREAD

**Issue by SuperPypok** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#14]
Hi, while making a mod for the drill, ran into a problem that causes the game to crash as soon as I load an item in my inventory.

MCreator version: 2023.1
Generator version: 1.19.2
GeckoLib plugin version: 4.7.1
Crash-report: https://github.com/SuperPypok/mcrah

(DeepL translate)

**Comment by NerdyPuzzle** [comment]
software.bernie.geckolib3.geo.exception.GeckoLibException: iron_drill:animations/iron_drill.animation.json: Could not find animation file. Please double check name.

this is one of the first lines in your crash report. pretty self-explanatory what you did wrong here.

**Comment by SuperPypok** [comment]
Thanks!
