### ISSUE TITLE
entitys dont naturally spawn

### ISSUE THREAD

**Issue by Thefarteater23** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#147]
animated entitys dont naturally spawn

**Comment by hampop** [comment]
all my animated entities spawn just fine most likely you did something wrong

**Comment by Thefarteater23** [comment]
none spawn for me, il test again tho

**Comment by Thefarteater23** [comment]
works now, idk what I was doing wrong lol, how do I delete a post?
