### ISSUE TITLE
bugs that need to be fixed

### ISSUE THREAD

**Issue by maxhaaaa** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#148]
yo nerdy, the plugin is functional but its really hard to use, you have to manually delete geckolib files from the resources tab otherwise the client breaks, most of the time animated items don't have a model, geckolib files have to be manually deleted and reimported to change them you can't just replace them like the old versions. but thats all thats wrong with this update. when you get the time to work on this please fix these, ill put it on github so you can keep track of this

**Comment by maxhaaaa** [comment]
issues as followed and any additional comments will be made at the end of each point, the comments are mainly just anything i think can help you pinpoint where exactly the issue is arrising from.
UNIMPORTANT================
i do programming for mcreator aswell, no where near your level but i at least semi know what you need and what can help .as someone who has to debug their own files aswell i know how annoying it is to read a bug report full of essentially usless information, so any comments will be made in brakets but im sure you found that out already,
===========================

version 1.20.1,
current mcreator version 2024.3, geckolib v5.9.1
upgraded from 2024.2 from geckolib V5.8.5, 
(i upgraded to 5.9 briefly before downgrading back, it shouldn't be an issue since i tested making a new workspace entirly, and the problems still persisted and yes i messed with V5.8.5 to make it work with 2024.3 but i tested if this was the issue several times and problems persisted)

1. most new animated items do not have a models, (strange enough freshly made models worked very briefly when they were made with newest version of geckolib, but when i changed them in blockbench and updated them in geckolib, they refused to work, maybe its somthing with the changes you made since this model had been changed in the past but broke after 1 new version in the newest geckolib if that makes sense)

2. old geckolib resources do not merge with new ones, (this is the one probably most people are affected by right now, i found when updating geckolib models, the only way it would actually apply the change is if i removed all traces of the old model, meaning i had to delete all animated items containing it and wipe is from the resource tab, i know this is the case because i found not doing this left you with unchanged models ingame, so just trying to overwrite like you could do in V5.8.5 normally wouldn't work in this version, so probably a file managment problem)

3. forementioned unchanged models will cause the client to break, (so as mentioned in the issue above, you can't overwrite geckolib resources like you regularly could back in V5.8.5, doing the method as said above will briefly make them work for a singlar version, then it will break in the same way as issue 1, however NOT doing this will make the testing environemnt return an error from auditory+17 thingy not ending in a 1, then the client crashes and gives a crash report.)


AGAIN UNIMPORTANT👇
i hope these help you nerdy, i know you got a life to, so don't worry about fixing these immdiently, people can last without their mcreator for a while if they are that dependant on your plugin. if it was up to me though, i would aim to fix the missing models first before the file management problems, since people are just going to going to report the same bugs

**Comment by NerdyPuzzle** [comment]
I have not been able to replicate not being able to replace or delete geckolib resources with the resources tab. The invisible items issue is caused by blockbench sometimes not adding the line "parent": "builtin/entity" to its display settings file. That is to say, I do not see any plugin bugs here.
