### ISSUE TITLE
Geckolib v5.9.1 breaks global triggers and procedures

### ISSUE THREAD

**Issue by sally3751** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#149]
After upgrading my mod from 2024.2's latest version to 2024.340615, the global triggers for my mods procedures don't work like they used to in NeoForge 1.20.6. The trigger in the image below is supposed to say "Player respawns", but instead it says "player_respawn". Even after changing the trigger to something else or reselecting the same trigger, the procedures are not fixed for me.

![mcreator_procedure_problem](https://github.com/user-attachments/assets/dbceb07c-ab84-41f2-aa2f-6ca66768c2c2)

- I have also tested this problem in a brand new workspace, and the global trigger problem persists even if Geckolib is disabled through Workspace Settings ----> External APIs. The problem goes away when I remove the Geckolib plugin from the .mcreator/plugins folder.

- If there are any additional files or information required to address this issue, I will do so as best as I can (workspaces, etc.).

**Comment by NerdyPuzzle** [comment]
So just a visual issue? Trigger works as intended?

**Comment by sally3751** [comment]
No, the procedures do not work in any way. They used to work properly in the past, but now they don't anymore after I tested the problem in-game after clicking on "Run client" in MCreator 2024.3 and NeoForge 1.21.1.

I have more information on the issue which I already submitted to the MCreator Team: ----> [https://github.com/MCreator/MCreator/issues/5138]

**Comment by sally3751** [comment]
Okay, after testing the problem in-game again, I found out there was nothing actually wrong with the triggers. I thought there WAS something actually wrong with my mod, and forgot that one of my mobs which uses that procedure I showed you is supposed to behave stealthily.

- So the triggers themselves work properly, but your plugin is causing the triggers to **look** weird in the Event Trigger block if that makes sense.

**Comment by MagicalAlexey** [comment]
I confirm this bug

**Comment by MateusKH** [comment]
Se for apenas visual, não importa muito.

**Comment by MateusKH** [comment]
If it's just visual, it doesn't matter much.
