### ISSUE TITLE
Crash: Game crashed whilst rendering overlay

### ISSUE THREAD

**Issue by SanMiguelZ** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#15]
I got an error which caused the game to crash every time I tried opening minecraft with my mod enabled.

MCreator Version: 2023.1
Generator Version: 1.19.2
Geckolib Plugin Version: 4.7.1
Crash Report: https://pastebin.com/PvehkB0w

Thanks!

**Comment by NerdyPuzzle** [comment]
something is wrong with your animation file or model file, not a plugin issue.

**Comment by SanMiguelZ** [comment]
Okay, thank you.

**Comment by SanMiguelZ** [comment]
Hi again, i deleted all of the animations and the error still had not been fixed, if you can, can you tell me what's wrong with it?
