### ISSUE TITLE
Cannot Add Animated Block Element to Workspace (v5.9.1, 2024.3)

### ISSUE THREAD

**Issue by RamenNoodlesGuyGJ** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#151]
The option to add a new GeckoLib animated block to the workspace in the New Element tab does not work. The window comes up to enter the name of the block, but once input no new element is created. This only occurs with the Animated Block; the Entity and Item elements work just fine.

**Comment by NerdyPuzzle** [comment]
Could not reproduce. Make sure you do not have multiple versions of the plugin in your plugin folder.
