### ISSUE TITLE
block compile fail 2024.3

### ISSUE THREAD

**Issue by rep3ater2121** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#152]
today i was developing my server mod and found myself creating a geckolib armor, that shouldnt be such a problem since when the minecraft dint run
i  just removed the element, but then i regenerated the code since i could open it anymore and found it couldnt load cus the blocks and a particle dint compile correctly(they worked fine before)(also got a character error but it stoppet it was somethin abt me writing "c~" wich is a character in my language) so i removed geckolib tried the 2 most common problem and it dint work, removed the blocks and elements and it noramlly just says one of my main mods is the problem
pls help fellas.
im running 1.20.1 geckolib latest version, the mcreator staff told me i should reach out to you.
i admire you for what you've done with you plugins as you havent just made the geckolib plugin but many others that have helped me in the past.
please help me for there were people that paid for my mod and i dont know what to tell em

https://www.mediafire.com/file/dxdvozhhmvkqpv0/my_post_traumatic_geckolib_experience.zip/file

**Comment by rep3ater2121** [comment]
https://pastebin.com/8L3aCCfu
build log

**Comment by NerdyPuzzle** [comment]
This is nothing to do with the plugin, this is gradle caches breaking.
