### ISSUE TITLE
Can't run minecraft with plugin's armour

### ISSUE THREAD

**Issue by rep3ater2121** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#154]
hey there ik u said the problem was my setup but i in fact tested on other devices and the error continued, sorry to be so annoying but it seems to be a recurring issue
as seen in these
[https://mcreator.net/forum/93978/why-my-game-doesnt-open-geckolib-plugin](url)
[https://www.reddit.com/r/MCreator/comments/1e29luu/comment/ld3v9vs/](url)
these r the 2 i found

this guy actually finds a way by changing the export mode on blockbench plugin idk if u r the owner of that one tho
[https://mcreator.net/forum/109386/game-freezes-loading-screen#google_vignette](url)
couldnt find the "logs he mentioned"

**Comment by NerdyPuzzle** [comment]
I can't solve issues with speculation. I need your crashlog.

**Comment by rep3ater2121** [comment]
> .

I could send the Minecraft crash log, the mcreator graddle js doesnt load

**Comment by NerdyPuzzle** [comment]
more than likely an issue with your model file as all these cases end up being. blockbench just loves to dish out broken models every now and then.
