### ISSUE TITLE
v.5.9.1 animated blocks cannot be created

### ISSUE THREAD

**Issue by SirMultiMan** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#155]
with the latest version of the plugin (v5.9.1) you simply cannot create animated blocks. You can press plus in the workspace and enter a name for the block, but no matter what you enter, as soon as you confirm, the window simply disappears again and the animated block is not created, please fix this

**Comment by NerdyPuzzle** [comment]
I need your mcreator.log. Find it in user/your user/.mcreator/logs

**Comment by NerdyPuzzle** [comment]
Nevermind, found the issue. They decided to rename a line of code for no reason in the latest patch.
