### ISSUE TITLE
Animated entity does not compile (2024.3)

### ISSUE THREAD

**Issue by Bones-X** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#156]
Hi,

I'm trying to create an animated entity but it does not compile (build failed). It is my first try (I'm kinda new to this type of things) and I checked everything many times; I could not find a solution to this problem, please have mercy and help me out.

This the error that shows up (the name of the entity is completely random, I just wanted to try):

`Executing Gradle task: runClient 
Build info: MCreator 2024.3.42716, neoforge-1.21.1, 64-bit, 6021 MB, Windows 11, JVM 21.0.4, JAVA_HOME: C:\Program Files\Pylo\MCreator\jdk, started on: 2024-10-30-21:37:20 
Loaded APIs: geckolib 
 
Reusing configuration cache. 
> Task :createArtifactManifest UP-TO-DATE 
> Task :downloadAssets UP-TO-DATE 
> Task :processResources UP-TO-DATE 
> Task :createMinecraftArtifacts UP-TO-DATE 
> Task :writeClientLegacyClasspath UP-TO-DATE 
> Task :prepareClientRun UP-TO-DATE 
> Task :compileJava FAILED 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\client\renderer\OefnisfadasdRenderer.java:4](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/client/renderer/OefnisfadasdRenderer.java:4): error: package software.bernie.geckolib.renderer does not exist 
import software.bernie.geckolib.renderer.GeoEntityRenderer; 
                                        ^ 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\client\renderer\OefnisfadasdRenderer.java:5](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/client/renderer/OefnisfadasdRenderer.java:5): error: package software.bernie.geckolib.cache.object does not exist 
import software.bernie.geckolib.cache.object.BakedGeoModel; 
                                            ^ 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\client\renderer\OefnisfadasdRenderer.java:18](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/client/renderer/OefnisfadasdRenderer.java:18): error: cannot find symbol 
public class OefnisfadasdRenderer extends GeoEntityRenderer<OefnisfadasdEntity> { 
                                          ^ 
  symbol: class GeoEntityRenderer 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:4](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:4): error: package software.bernie.geckolib.util does not exist 
import software.bernie.geckolib.util.GeckoLibUtil; 
                                    ^ 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:5](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:5): error: package software.bernie.geckolib.animation does not exist 
import software.bernie.geckolib.animation.RawAnimation; 
                                         ^ 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:6](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:6): error: package software.bernie.geckolib.animation does not exist 
import software.bernie.geckolib.animation.PlayState; 
                                         ^ 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:7](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:7): error: package software.bernie.geckolib.animation does not exist 
import software.bernie.geckolib.animation.AnimationState; 
                                         ^ 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:8](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:8): error: package software.bernie.geckolib.animation does not exist 
import software.bernie.geckolib.animation.AnimationController; 
                                         ^ 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:9](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:9): error: package software.bernie.geckolib.animation does not exist 
import software.bernie.geckolib.animation.AnimatableManager; 
                                         ^ 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:10](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:10): error: package software.bernie.geckolib.animatable.instance does not exist 
import software.bernie.geckolib.animatable.instance.AnimatableInstanceCache; 
                                                   ^ 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:11](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:11): error: package software.bernie.geckolib.animatable does not exist 
import software.bernie.geckolib.animatable.GeoEntity; 
                                          ^ 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:38](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:38): error: cannot find symbol 
public class OefnisfadasdEntity extends Monster implements GeoEntity { 
                                                           ^ 
  symbol: class GeoEntity 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\client\renderer\OefnisfadasdRenderer.java:30](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/client/renderer/OefnisfadasdRenderer.java:30): error: cannot find symbol 
    public void preRender(PoseStack poseStack, OefnisfadasdEntity entity, BakedGeoModel model, MultiBufferSource bufferSource, VertexConsumer buffer, boolean isReRender, float partialTick, int packedLight, int packedOverlay, int color) { 
                                                                          ^ 
  symbol:   class BakedGeoModel 
  location: class OefnisfadasdRenderer 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:42](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:42): error: cannot find symbol 
    private final AnimatableInstanceCache cache = GeckoLibUtil.createInstanceCache(this); 
                  ^ 
  symbol:   class AnimatableInstanceCache 
  location: class OefnisfadasdEntity 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:133](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:133): error: cannot find symbol 
    private PlayState movementPredicate(AnimationState event) { 
                                        ^ 
  symbol:   class AnimationState 
  location: class OefnisfadasdEntity 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:133](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:133): error: cannot find symbol 
    private PlayState movementPredicate(AnimationState event) { 
            ^ 
  symbol:   class PlayState 
  location: class OefnisfadasdEntity 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:148](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:148): error: cannot find symbol 
    private PlayState attackingPredicate(AnimationState event) { 
                                         ^ 
  symbol:   class AnimationState 
  location: class OefnisfadasdEntity 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:148](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:148): error: cannot find symbol 
    private PlayState attackingPredicate(AnimationState event) { 
            ^ 
  symbol:   class PlayState 
  location: class OefnisfadasdEntity 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:168](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:168): error: cannot find symbol 
    private PlayState procedurePredicate(AnimationState event) { 
                                         ^ 
  symbol:   class AnimationState 
  location: class OefnisfadasdEntity 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:168](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:168): error: cannot find symbol 
    private PlayState procedurePredicate(AnimationState event) { 
            ^ 
  symbol:   class PlayState 
  location: class OefnisfadasdEntity 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:203](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:203): error: package AnimatableManager does not exist 
    public void registerControllers(AnimatableManager.ControllerRegistrar data) { 
                                                     ^ 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:210](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:210): error: cannot find symbol 
    public AnimatableInstanceCache getAnimatableInstanceCache() { 
           ^ 
  symbol:   class AnimatableInstanceCache 
  location: class OefnisfadasdEntity 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\model\OefnisfadasdModel.java:3](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/model/OefnisfadasdModel.java:3): error: package software.bernie.geckolib.model does not exist 
import software.bernie.geckolib.model.GeoModel; 
                                     ^ 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\model\OefnisfadasdModel.java:9](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/model/OefnisfadasdModel.java:9): error: cannot find symbol 
public class OefnisfadasdModel extends GeoModel<OefnisfadasdEntity> { 
                                       ^ 
  symbol: class GeoModel 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\client\renderer\OefnisfadasdRenderer.java:21](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/client/renderer/OefnisfadasdRenderer.java:21): error: cannot find symbol 
        this.shadowRadius = 0.5f; 
            ^ 
  symbol: variable shadowRadius 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\client\renderer\OefnisfadasdRenderer.java:24](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/client/renderer/OefnisfadasdRenderer.java:24): error: method does not override or implement a method from a supertype 
    @Override 
    ^ 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\client\renderer\OefnisfadasdRenderer.java:26](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/client/renderer/OefnisfadasdRenderer.java:26): error: cannot find symbol 
        return RenderType.entityTranslucent(getTextureLocation(animatable)); 
                                            ^ 
  symbol:   method getTextureLocation(OefnisfadasdEntity) 
  location: class OefnisfadasdRenderer 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\client\renderer\OefnisfadasdRenderer.java:29](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/client/renderer/OefnisfadasdRenderer.java:29): error: method does not override or implement a method from a supertype 
    @Override 
    ^ 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\client\renderer\OefnisfadasdRenderer.java:32](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/client/renderer/OefnisfadasdRenderer.java:32): error: cannot find symbol 
        this.scaleHeight = scale; 
            ^ 
  symbol: variable scaleHeight 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\client\renderer\OefnisfadasdRenderer.java:33](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/client/renderer/OefnisfadasdRenderer.java:33): error: cannot find symbol 
        this.scaleWidth = scale; 
            ^ 
  symbol: variable scaleWidth 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\client\renderer\OefnisfadasdRenderer.java:34](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/client/renderer/OefnisfadasdRenderer.java:34): error: cannot find symbol 
        super.preRender(poseStack, entity, model, bufferSource, buffer, isReRender, partialTick, packedLight, packedOverlay, color); 
        ^ 
  symbol:   variable super 
  location: class OefnisfadasdRenderer 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\client\renderer\OefnisfadasdRenderer.java:37](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/client/renderer/OefnisfadasdRenderer.java:37): error: method does not override or implement a method from a supertype 
    @Override 
    ^ 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:42](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:42): error: cannot find symbol 
    private final AnimatableInstanceCache cache = GeckoLibUtil.createInstanceCache(this); 
                                                  ^ 
  symbol:   variable GeckoLibUtil 
  location: class OefnisfadasdEntity 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:138](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:138): error: cannot find symbol 
                return event.setAndContinue(RawAnimation.begin().thenLoop("walking")); 
                                            ^ 
  symbol:   variable RawAnimation 
  location: class OefnisfadasdEntity 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:141](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:141): error: cannot find symbol 
                return event.setAndContinue(RawAnimation.begin().thenLoop("tweaking")); 
                                            ^ 
  symbol:   variable RawAnimation 
  location: class OefnisfadasdEntity 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:143](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:143): error: cannot find symbol 
            return event.setAndContinue(RawAnimation.begin().thenLoop("idle")); 
                                        ^ 
  symbol:   variable RawAnimation 
  location: class OefnisfadasdEntity 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:145](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:145): error: cannot find symbol 
        return PlayState.STOP; 
               ^ 
  symbol:   variable PlayState 
  location: class OefnisfadasdEntity 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:159](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:159): error: package AnimationController does not exist 
        if (this.swinging && event.getController().getAnimationState() == AnimationController.State.STOPPED) { 
                                                                                             ^ 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:161](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:161): error: cannot find symbol 
            return event.setAndContinue(RawAnimation.begin().thenPlay("attack")); 
                                        ^ 
  symbol:   variable RawAnimation 
  location: class OefnisfadasdEntity 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:163](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:163): error: cannot find symbol 
        return PlayState.CONTINUE; 
               ^ 
  symbol:   variable PlayState 
  location: class OefnisfadasdEntity 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:169](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:169): error: package AnimationController does not exist 
        if (!animationprocedure.equals("empty") && event.getController().getAnimationState() == AnimationController.State.STOPPED || (!this.animationprocedure.equals(prevAnim) && !this.animationprocedure.equals("empty"))) { 
                                                                                                                   ^ 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:172](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:172): error: cannot find symbol 
            event.getController().setAnimation(RawAnimation.begin().thenPlay(this.animationprocedure)); 
                                               ^ 
  symbol:   variable RawAnimation 
  location: class OefnisfadasdEntity 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:173](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:173): error: package AnimationController does not exist 
            if (event.getController().getAnimationState() == AnimationController.State.STOPPED) { 
                                                                                ^ 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:179](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:179): error: cannot find symbol 
            return PlayState.STOP; 
                   ^ 
  symbol:   variable PlayState 
  location: class OefnisfadasdEntity 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:182](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:182): error: cannot find symbol 
        return PlayState.CONTINUE; 
               ^ 
  symbol:   variable PlayState 
  location: class OefnisfadasdEntity 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:202](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:202): error: method does not override or implement a method from a supertype 
    @Override 
    ^ 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:204](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:204): error: cannot find symbol 
        data.add(new AnimationController<>(this, "movement", 4, this::movementPredicate)); 
                     ^ 
  symbol:   class AnimationController 
  location: class OefnisfadasdEntity 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:205](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:205): error: cannot find symbol 
        data.add(new AnimationController<>(this, "attacking", 4, this::attackingPredicate)); 
                     ^ 
  symbol:   class AnimationController 
  location: class OefnisfadasdEntity 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:206](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:206): error: cannot find symbol 
        data.add(new AnimationController<>(this, "procedure", 4, this::procedurePredicate)); 
                     ^ 
  symbol:   class AnimationController 
  location: class OefnisfadasdEntity 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\OefnisfadasdEntity.java:209](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/OefnisfadasdEntity.java:209): error: method does not override or implement a method from a supertype 
    @Override 
    ^ 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\model\OefnisfadasdModel.java:10](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/model/OefnisfadasdModel.java:10): error: method does not override or implement a method from a supertype 
    @Override 
    ^ 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\model\OefnisfadasdModel.java:15](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/model/OefnisfadasdModel.java:15): error: method does not override or implement a method from a supertype 
    @Override 
    ^ 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\entity\model\OefnisfadasdModel.java:20](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/entity/model/OefnisfadasdModel.java:20): error: method does not override or implement a method from a supertype 
    @Override 
    ^ 
[C:\Users\edoar\MCreatorWorkspaces\vuldanar\src\main\java\net\mcreator\vuldanar\init\VuldanarModEntityRenderers.java:18](file:///C:/Users/edoar/MCreatorWorkspaces/vuldanar/src/main/java/net/mcreator/vuldanar/init/VuldanarModEntityRenderers.java:18): error: method registerEntityRenderer in class RegisterRenderers cannot be applied to given types; 
        event.registerEntityRenderer(VuldanarModEntities.OEFNISFADASD.get(), OefnisfadasdRenderer::new); 
             ^ 
  required: EntityType<? extends T>,EntityRendererProvider<T> 
  found:    EntityType<OefnisfadasdEntity>,Oefnisfada[...]::new 
  reason: cannot infer type-variable(s) T 
    (argument mismatch; bad return type in method reference 
      OefnisfadasdRenderer cannot be converted to EntityRenderer<T>) 
  where T is a type-variable: 
    T extends Entity declared in method <T>registerEntityRenderer(EntityType<? extends T>,EntityRendererProvider<T>) 
54 errors 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':compileJava'. 
> Compilation failed; see the compiler error output for details. 
* Try: 
> Run with --info option to get more log output. 
> Run with --scan to get full insights. 
BUILD FAILED in 3s 
7 actionable tasks: 1 executed, 6 up-to-date 
Configuration cache entry reused. 
 
BUILD FAILED 
Task completed in 5 seconds`

**Comment by NerdyPuzzle** [comment]
Either you didnt enable the api or your gradle cache is corrupted

**Comment by Bones-X** [comment]
Unfortunately the API is enabled so I think I might have to reset everything ;(

**Comment by Bones-X** [comment]
> Either you didnt enable the api or your gradle cache is corrupted

Unfortunately the API is enabled so I think I might have to reset everything ;(
