### ISSUE TITLE
Shaking Entities and Items

### ISSUE THREAD

**Issue by IeuanBell** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#165]
MCreator Version: 2023.2

I've made a report about the item shaking already with a video of what's happening, its issue #150 atm, and I've discovered that entities do basically the exact same thing. They are completely fine for the most part, but after looking at them for a long period of time they start to shake more and more until eventually the model is rag-dolling transparently through the air above them. It's essentially the same visual bug as items, which can be viewed on the video I linked.

**Comment by NerdyPuzzle** [comment]
2023.2 is not going to receive any further updates.
