### ISSUE TITLE
Dimension receiving mineables tags and not properly initializing on ModBlocks and ModItems files

### ISSUE THREAD

**Issue by Marianz222** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#167]
I have a custom dimension on my workspace and it recently broke (Not sure if it was because I updated another plugin, the Blockstates one or if it was because I did something wrong on the workspace) But I can't enter the test session because suppossedly there are 2 entries on the "ModBlocks.java" and "ModItems.java" init files that give errors, those 2 entries are the dimension block portal and the dimension igniter item. I checked the entries and they seem normal, they are registered correctly (The entries look exactly the same as others in the same file, using the REGISTRY.register method and the right parameters, but still gives an error. After that I tried editing the dimension element, but discovered that the code files cannot be edited with the Edit Code option, neither java or json files work with that, and the only files I can edit are the ModBlocks and ModItems registry files, also the "overworld_carver_replaceables" tag, but nothing more.

Another peculiar thing I saw is that the dimension mod element has tags attached to it, for some reason, and these are the following:
- "minecraft:tags/blocks/mineable/pickaxe.json"
- "minecraft:tags/blocks/mineable/axe.json"
- "minecraft:tags/blocks/mineable/hoe.json"
- "minecraft:tags/blocks/mineable/shovel.json"

I checked if removing the Gecko plugin and reloading the Workspace would fix this, and the dimension didn't have those tags and registry issues anymore, so I assume this is a bug with Geckolib, but could be a strange byproduct of combining various plugins together. Idk, here is the link to the post with both images, the first one is on the main workspace but I removed Geckolib and now I can actually edit the dimension code and the mineable tags are not there, the second one is adding back the plugin and regenerating the code to once more see the tags and the error pop up:

[Dimension Element Comparison](https://imgur.com/a/DASaOqT) (Sorry for the bad quality on the second picture, had to take it with my phone cause the second screenshot wasn't capturing the little edit element window for some odd reason)

This is the mcreator console log: [MCreator Console Log](https://pastebin.com/8PZFJCie)

My specifications for what i'm using:
- MCreator version: 2023.4 (release)
- Geckolib plugin version: 5.6.6 (release)
- Other plugins included in the workspace: Additions, Armor Trims, Attributes, Blockstates, Configuration Files, Forge Mixins, Item Tooltips, Just Enough Recipes, MCreator VCS, Particle Models, Pehkui, Snails Plugin, Toasts 2, World Renderer.

The big issue with this for me is that unless you send me a previous build for MCreator 2023.4 (Like Gecko 5.6.5 or something previous to this one) I cannot continue to work on the workspace since I needed to release an update for my mod on 1.19.4, and that generator is no longer supported on newer builds of MCreator, so if you update the main plugin path and patch the issue I couldn't update, unless the update also goes to the 2023.4 version, but I don't blame you if you can't go back and update the old builds. Still, I don't know if the plugin is the issue but seems possible, hope all of this info is useful, if you need more I will provide. Thanks!

**Comment by NerdyPuzzle** [comment]
This does not happen in the latest version and version 2023.4 is not going to receive any new updates.
