### ISSUE TITLE
GeckoLib 4.7.1 Makes MCreator 2023.1 freeze

### ISSUE THREAD

**Issue by Zachadactyl** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#17]
With MCreator 2023.1 installed on MacOS 13.3 and Nerdy's GeckoLib Plugin v4.7.1 MCreator will freeze either opening previous 2023.1 mods (as in, I made before installing the plugin)as well as when hitting the Add New and selecting Forge 1.19.2.  I have no other plugins installed.  v3.5.1 works in MCreator 2022.3

**Comment by Zachadactyl** [comment]
In MCreator Discord TaedetOmnia had a temp fix, they say you're fixing for the next update. This may  or may not be different.

**Comment by NerdyPuzzle** [comment]
already fixed, will be part of the next update
