### ISSUE TITLE
Animated Blocks Causing Decreased Mining Speed Issue in Geckolib3

### ISSUE THREAD

**Issue by VKHSD** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#18]
Hello,

I am experiencing an issue with the mining speed of my animated blocks in my mod. I am using the GeckoLib library to create the animations, and I have noticed that when I mine the blocks, the mining speed is significantly slower than it should be.

I have narrowed down the issue to the use of the GeckoLib library, as when I remove the animations and use regular blocks, the mining speed is normal.

I would appreciate it if someone from the GeckoLib development team could provide some insight into why this might be happening and if there is a solution.

Thank you.

**Comment by NerdyPuzzle** [comment]
I'll look into it when I have some time. Also, I am not the geckolib development team, I just made a plugin to add support for a mod that existed before this plugin.

**Comment by VKHSD** [comment]
I am aware you aren’t part of the geckolib team and I thank you for making this tool, I have asked around and nobody seems to know or care about this issue. I hope youll see to it. But I restate that, if an animated block that uses your geckolib plugin exists within a workspace in mcreator, then all other custom blocks within that space ignore all destruction parameters such as hardness and the tools able to destroy it. Thanks for seeing this concern, I hope it is fixed or you can provide some insight on how I myself may fix it and again, thanks.


Tommy Izo

Undefined or “Undefined Calx”

undefined.bandcamp.com
