### ISSUE TITLE
Hello, I have a problem with a loop animation

### ISSUE THREAD

**Issue by bettendone3** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#21]
I'm making an entity that sleeps but the problem is that when it "finishes" the animation wakes up and automatically runs the animation again.

(Sorry Nerdy's Puzzle for bothering you)

**Comment by NerdyPuzzle** [comment]
Use the loop condition in the entity element.

**Comment by NerdyPuzzle** [comment]
This place is fir issues with the plugin, not support.
