### ISSUE TITLE
Animated Item not working with Keybind?

### ISSUE THREAD

**Issue by MichaelMichelle2** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#22]
I am attempting to make a retractable shield using a keybind to retract and expand the shield, but nothing happens. The text I have appears, but the animations don't play. I put this as an issue incase it was the procedure and keybind, and not the code.

![Screenshot 2023-04-17 231538](https://user-images.githubusercontent.com/96556558/232687756-fce390d5-e4da-4f12-9cd7-3b4813c6bb63.png)

**Comment by NerdyPuzzle** [comment]
replace every item procedure block with item in main hand of event-target entity.

**Comment by MichaelMichelle2** [comment]
Thank you, now I need to figure out how it doesn't switch back to idle when it retracts. As in idle the shield is out still.
