### ISSUE TITLE
(Fabric 1.19.2) Animations with loop type "hold_on_last_frame" don't work on blocks

### ISSUE THREAD

**Issue by clarence112** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#24]
Expected result:
![sem2](https://user-images.githubusercontent.com/20058567/235415914-330e0da0-b7b9-4f86-83a0-01bd5404bac8.gif)

Current result:
![sem3](https://user-images.githubusercontent.com/20058567/235415953-718ed0e2-0fe1-433e-90df-2cee4b5e5d7d.gif)

Procedure I'm using:
![image](https://user-images.githubusercontent.com/20058567/235416998-6adbadf8-9ac2-4e5b-a8ce-f39915ae1ecb.png)

I'm willing to edit any java code I need to if a fix is unable to be implemented in the module

**Comment by clarence112** [comment]
How do I do it manually in the code then?

**Comment by clarence112** [comment]
There isn't a fabric plugin for 1.19.4, and even if there was the mods I'm trying to be compatible with don't support it either. I'm kinda stuck here and the geckolib docs are completely unhelpful

**Comment by NerdyPuzzle** [comment]
this place is for issues with the plugin, nothing is wrong with the plugin.
