### ISSUE TITLE
Blocks cause Build Error 1.19.4 + cant create animated blocks

### ISSUE THREAD

**Issue by AcidDrink69** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#25]
Enabling the GeckoLib plug-in for the latest 2023.2 snapshot causes Blocks to have build errors for some reason and Animated blocks cannot be created. After typing in a name for the Animated Block Element, the box just disappears and nothing happens. Nothing in the log also.

**Comment by NerdyPuzzle** [comment]
fixed
