### ISSUE TITLE
Feature Request: Sitting Built-In Animation

### ISSUE THREAD

**Issue by Spiderach** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#29]
Seeing as there's built in "Sitting" nbt on tamed entities that is completely functional at preventing movement without the need for extra procedures, it'd be really nice if that nbt state could be used to automatically set an "animation"(in my case just a pose) for that state.

   As is I've had to do a massive workaround to get that behavior and state to toggle where I had to re-write the sitting functionality with procedures for toggling the state and checks for AI blocks. Even with all of that for the life of me I couldn't get that one-frame pose animation to work reliably with a custom number NBT tag. Despite using a simple numerical NBT check, it always either:

A) Didn't trigger at all
B) Triggered on the wrong state despite it being an if x=0 then do A , if x=1 then do B, etc
C) Most often just got stuck on the animation

   These happened regardless of if I used the entity animation condition, dedicated global trigger procedure, or the right-click interact procedure (all with different wrong results).

   In the end I just piggybacked off of the sneak condition, which worked flawlessly first try. Thankfully I didn't intend to use the sneak functionality of the entity anyway.

   All that being said making use of the "Sitting" status built into tamed mobs would be really useful.

**Comment by pringlethegoat** [comment]
Thanks for the Workaround / Piggybacking Technique, would love to see this added as a Feature too as I'm having issues with getting Procedure Animation(s) working properly with NBT data. Sad to see that this isn't already a Feature with just default MCreator- hopefully one day though!
