### ISSUE TITLE
Remove Geckolib Icon

### ISSUE THREAD

**Issue by AzureDoom** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#3]
As the owner of the current Geckolib branding artwork, you do not have my permission to use the Geckolib branding. https://mcreator.net/plugin/91484/nerdys-geckolib-plugin-forge-1182-1192

Please kindly remove my artwork and take notice that we will still ban any users attempting to use this on the Geckolib discord, so I suggest giving notice of this as well on your **unofficial and unsupported** plugin.

**Comment by NerdyPuzzle** [comment]
![geckolib_2](https://user-images.githubusercontent.com/112079900/197774819-da6b9fc9-e374-455c-b230-30c3e79d44a6.png)
Noted. Is this an acceptable replacement?

**Comment by AzureDoom** [comment]
> ![geckolib_2](https://user-images.githubusercontent.com/112079900/197774819-da6b9fc9-e374-455c-b230-30c3e79d44a6.png) Noted. Is this an acceptable replacement?

Yes, thank you.
