### ISSUE TITLE
Missing symbols error not fixed

### ISSUE THREAD

**Issue by jhe675** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#33]
Mod is fully loaded, Java plugins enabled. Up to date for MCreator 2023.2 Forge 1.19.4, for geckolib plugin v4.8.7. Help appreciated thanks. Happens when I try running anything btw, gets stuck on compileJava and then in console shows hundreds of missing symbol errors.

I have enabled geckolib API from workspace settings yet it shows the same error

**Comment by NerdyPuzzle** [comment]
I cannot help fix what I cannot find any way to reproduce using only my plugin. As I said in the other issue, remove any other geckolib plugins or old versions and try again. If that doesn't work, remove all other plugins except this.

**Comment by jhe675** [comment]
Could I send you my workspace so you can identify the problem? I have deleted all possible versions, maybe I have the plugin in the wrong folder I am not sure

**Comment by jhe675** [comment]
how can I send it to you

**Comment by jhe675** [comment]
also wait, what folders should the plugin be in? just to make sure

**Comment by NerdyPuzzle** [comment]
export it 
![image](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/112079900/44761828-2eb3-45dd-a029-711497736737)

**Comment by NerdyPuzzle** [comment]
> also wait, what folders should the plugin be in? just to make sure
you just click load plugin in the manage plugins preferences page

**Comment by jhe675** [comment]
ok yeah its there thanks. how would i upload this

**Comment by NerdyPuzzle** [comment]
paste it here

**Comment by jhe675** [comment]
file size too big

**Comment by NerdyPuzzle** [comment]
the just upload it on mediafire or something

**Comment by jhe675** [comment]
google drive is fine?

**Comment by jhe675** [comment]
sorry if this is taking your time too much

**Comment by jhe675** [comment]
https://drive.google.com/file/d/1ZhOv3H7n7wBPRXxojYINZqNyzh9ZNQyf/view?usp=sharing

**Comment by jhe675** [comment]
does it show the same error for you?

**Comment by jhe675** [comment]
> as long as I can download it I don't care where it is


have you found anything yet?

**Comment by jhe675** [comment]
> as long as I can download it I don't care where it is

anything?

**Comment by jhe675** [comment]
@NerdyPuzzle did you download it ok? and also did you encounter the same error
