### ISSUE TITLE
Ranged item does not work with java model with geckolib enabled. What should I do is a bug?

### ISSUE THREAD

**Issue by SlashBro31** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#34]
![NylAqTcV37I](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/137270200/6137da8e-5cb1-46ca-a6dc-a21348b1df67)

**Comment by NerdyPuzzle** [comment]
This plugin does not do anything to ranged items.
