### ISSUE TITLE
Missing symbols error

### ISSUE THREAD

**Issue by jhe675** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#37]
100s of missing symbol errors
I submitted my workspace to have a look at it, and I've asked stuff but haven't got a response. Have you found any errors and how to fix them? Thanks

**Comment by NerdyPuzzle** [comment]
I did not have access to your google drive. Give me a download link I can use if you want me to test your workspace.

**Comment by jhe675** [comment]
> I did not have access to your google drive. Give me a download link I can use if you want me to test your workspace.

Can you access?

**Comment by NerdyPuzzle** [comment]
Yes and your errors have nothing to do with the plugin. Tons of unrelated minecraft classes are causing missing symbol errors too. Therefore, I do not have any reason to help you with this issue here as this page is only for issues relating to the plugin.

**Comment by jhe675** [comment]
Oh, when I put it on the main MCreator errors they said it was to do with the plugin.. idk what they were on about
Thank you, and sorry for wasting your time

**Comment by jhe675** [comment]
> Yes and your errors have nothing to do with the plugin. Tons of unrelated minecraft classes are causing missing symbol errors too. Therefore, I do not have any reason to help you with this issue here as this page is only for issues relating to the plugin.

Ok, so when I asked MCreator support, they said:
"Some plugins is overriding some important generator files. This is a plugin problem."

**Comment by jhe675** [comment]
I have no other plugins installed btw

**Comment by jhe675** [comment]
"error: package software.bernie.geckolib3 does not exist

This error can't be caused by MCreator as MCreator does not provide anything geckolib related to be able to emit this error.

Please consult with plugin author. This tracker is for core software bugs"

**Comment by NerdyPuzzle** [comment]
I suggest you head over to your workspace's folder and delete the .mcreator and .gradle folders

**Comment by jhe675** [comment]
thanks but still same error...

**Comment by jhe675** [comment]
> I suggest you head over to your workspace's folder and delete the .mcreator and .gradle folders

i've tried this multiple times and it never fixes it

**Comment by jhe675** [comment]
> 

that didnt do anything but thanks for suggesting

**Comment by NerdyPuzzle** [comment]
go for it if you want but from what I see this has nothing to do with my plugin.

**Comment by jhe675** [comment]
> go for it if you want but from what I see this has nothing to do with my plugin.

I have looked through the logs, heres what I found: https://gist.github.com/jhe675/ac66c2df4b1d4d4974fc7bbc168fdc50
If you look at it, you can see the missing symbols errors only show next to the animation code, and it only shows to geckolib entites. So I am 99% confident it is a plugin error

**Comment by NerdyPuzzle** [comment]
And from what I see here I am 99.9% confident that this error is completely on your end and would not happen if you were to install MCreator 2023.2 along with the latest version of my plugin and make a workspace. Please stop asking for help on something I told you many times is not an issue with the plugin's code.
