### ISSUE TITLE
Animated Armor body section broken (Fabric)

### ISSUE THREAD

**Issue by Bogieloo** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#39]
![image](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/99389439/21d12fec-9bf4-49b5-ae32-3e78a017d651)
This supposed to happen? (Fabric 1.19.2, 2023.2)

**Comment by NerdyPuzzle** [comment]
I noticed it, it's just a missing translation key. I'll fix it next update.

**Comment by NerdyPuzzle** [comment]
fixed
