### ISSUE TITLE
Could not load animation: "nameofanimation"

### ISSUE THREAD

**Issue by Dolontrolonto** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#4]
I have followed the tutorial and I have done everything well, I have repeated it several times with different versions of the plugin and mcreator, and different models and simpler animations, but always, when entering a world and generating the entity, the model looks fine but no animation is played and in the console it says "Could not load animation: walk" for example.

[Console logs](https://pastebin.com/x8mNC1XY)
[Model](https://www.mediafire.com/file/e8q8tzvpxr3v5z2/model.zip/file)
[Exported Workspace](https://www.mediafire.com/file/souzv2lx5s54v2r/exported+workspace.zip/file)

Please help me.

**Comment by NerdyPuzzle** [comment]
![Screenshot_455](https://user-images.githubusercontent.com/112079900/198844673-3296ff67-1b37-40fd-aa9f-86a45abeccb2.png)
Not a plugin issue. You just didn't follow the tutorial correctly.
![Screenshot_456](https://user-images.githubusercontent.com/112079900/198844756-8d664e04-1660-4089-9bde-cea990fd6806.png)
