### ISSUE TITLE
Rendering Overlay Error

### ISSUE THREAD

**Issue by Minticle** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#43]
Hey NerdyPuzzle. i wasn't originally going to come to you for this because i don't believe it's an error with this plugin, but Klemen claims that it's a problem with geckolib. any time that i try to load my client in MCreator, it crashes with an rendering overlay error. i'll attach the pastebin below, any help would be appreciated

https://pastebin.com/P9tMr3DM

**Comment by Minticle** [comment]
a little update, i've removed all my geckolib entities and removed the plugin, and it only crashes when geckolib api is enabled. if geckolib is not enabled then it loads fine, so it is a plugin problem

**Comment by NerdyPuzzle** [comment]
It is not a plugin problem. Reading the crash report, you have a broken animation file in your mods animation folder which crashes geckolib when it loads it. Go in your workspace files and find it then delete it.
