### ISSUE TITLE
I can't add animated block, armour, entity (Nerdy's GeckoLib Plugin)

### ISSUE THREAD

**Issue by PerdynStary** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#48]
Why I can't add animated block, armour, entity? Like i I click on the + button, then click on one of the above buttons, enter a name, click create and nothing is created. Help me please (I have Mccreator 2023.2, i made mode for Minecraft 1.19.2, geckolib api is turn on). And yeah animated item i can add

**Comment by NerdyPuzzle** [comment]
You just have the wrong version for your mcreator version.
