### ISSUE TITLE
Unable to create custom items (but can create blocks, armour, entities)

### ISSUE THREAD

**Issue by Kizwiz** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#49]
For some reason when I create custom animated items with your plugin it fails to compile. I am however able to create blocks, armour and entities. I have created the items carefully following your tutorial and doing everything as it should be done. When I tried to save/compile/load the mod it gives me this error in the console:

`Executing Gradle task: build 
Build info: MCreator 2023.2.24119, forge-1.19.2, 64-bit, 32693 MB, Windows 10, JVM 17.0.5, JAVA_HOME: C:\Program Files\Pylo\MCreator\jdk, started on: 2023-08-21-23:43:40 
  
> Configure project : 
The code of this workspace uses official obfuscation mappings provided by Mojang. These mappings fall under their associated license you should be fully aware of. 
(c) 2020 Microsoft Corporation. These mappings are provided "as-is" and you bear the risk of using them. You may copy and use the mappings for development purposes, 
but you may not redistribute the mappings complete and unmodified. Microsoft makes no warranties, express or implied, with respect to the mappings provided here. 
Use and modification of this document or the source code (in any form) of Minecraft: Java Edition is governed by the Minecraft End User License Agreement available 
at https://account.mojang.com/documents/minecraft_eula. 
  
> Task :compileJava 
[C:\Users\Joel\MCreatorWorkspaces\burrows\src\main\java\net\mcreator\burrows\item\renderer\StaffItemRenderer.java:63](file:///C:/Users/Joel/MCreatorWorkspaces/burrows/src/main/java/net/mcreator/burrows/item/renderer/StaffItemRenderer.java:63): error: cannot find symbol 
   private final Map<String, Vector3f> queuedBoneSetMovements = new HashMap<>(); 
                             ^ 
  symbol:   class Vector3f 
  location: class StaffItemRenderer 
[C:\Users\Joel\MCreatorWorkspaces\burrows\src\main\java\net\mcreator\burrows\item\renderer\StaffItemRenderer.java:64](file:///C:/Users/Joel/MCreatorWorkspaces/burrows/src/main/java/net/mcreator/burrows/item/renderer/StaffItemRenderer.java:64): error: cannot find symbol 
   private final Map<String, Vector3f> queuedBoneSetRotations = new HashMap<>(); 
                             ^ 
  symbol:   class Vector3f 
  location: class StaffItemRenderer 
[C:\Users\Joel\MCreatorWorkspaces\burrows\src\main\java\net\mcreator\burrows\item\renderer\StaffItemRenderer.java:65](file:///C:/Users/Joel/MCreatorWorkspaces/burrows/src/main/java/net/mcreator/burrows/item/renderer/StaffItemRenderer.java:65): error: cannot find symbol 
   private final Map<String, Vector3f> queuedBoneAddRotations = new HashMap<>(); 
                             ^ 
  symbol:   class Vector3f 
  location: class StaffItemRenderer 
C:\Users\Joel\MCreatorWorkspaces\burrows\src\main\java\net\mcreator\burrows\item\renderer\StaffItemRenderer.java:104: warning: [removal] getUniqueID(T) in GeoItemRenderer has been deprecated and marked for removal 
   public Integer getUniqueID(StaffItem animatable) { 
                  ^ 
  where T is a type-variable: 
    T extends Item,IAnimatable declared in class GeoItemRenderer 
C:\Users\Joel\MCreatorWorkspaces\burrows\src\main\java\net\mcreator\burrows\item\renderer\StaffItemRenderer.java:108: warning: [removal] getUniqueID(T) in GeoItemRenderer has been deprecated and marked for removal 
      return super.getUniqueID(animatable); 
                  ^ 
  where T is a type-variable: 
    T extends Item,IAnimatable declared in class GeoItemRenderer 
[C:\Users\Joel\MCreatorWorkspaces\burrows\src\main\java\net\mcreator\burrows\item\renderer\StaffItemRenderer.java:137](file:///C:/Users/Joel/MCreatorWorkspaces/burrows/src/main/java/net/mcreator/burrows/item/renderer/StaffItemRenderer.java:137): error: cannot find symbol 
      this.queuedBoneSetMovements.put(name, new Vector3f(x, y, z)); 
                                                ^ 
  symbol:   class Vector3f 
  location: class StaffItemRenderer 
[C:\Users\Joel\MCreatorWorkspaces\burrows\src\main\java\net\mcreator\burrows\item\renderer\StaffItemRenderer.java:141](file:///C:/Users/Joel/MCreatorWorkspaces/burrows/src/main/java/net/mcreator/burrows/item/renderer/StaffItemRenderer.java:141): error: cannot find symbol 
      this.queuedBoneAddRotations.put(name, new Vector3f(x, y, z)); 
                                                ^ 
  symbol:   class Vector3f 
  location: class StaffItemRenderer 
[C:\Users\Joel\MCreatorWorkspaces\burrows\src\main\java\net\mcreator\burrows\item\renderer\StaffItemRenderer.java:145](file:///C:/Users/Joel/MCreatorWorkspaces/burrows/src/main/java/net/mcreator/burrows/item/renderer/StaffItemRenderer.java:145): error: cannot find symbol 
      this.queuedBoneSetRotations.put(name, new Vector3f(x, y, z)); 
                                                ^ 
  symbol:   class Vector3f 
  location: class StaffItemRenderer 
6 errors 
2 warnings 
> Task :compileJava FAILED 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':compileJava'. 
> Compilation failed; see the compiler error output for details. 
* Try: 
> Run with --stacktrace option to get the stack trace. 
> Run with --info or --debug option to get more log output. 
> Run with --scan to get full insights. 
* Get more help at https://help.gradle.org 
BUILD FAILED in 3s 
1 actionable task: 1 executed 
  
BUILD FAILED 
Task completed in 6 seconds`

If you wish to check through the workspace, Nerdy, please let me know and I shall send the files via Discord.

**Comment by NerdyPuzzle** [comment]
unfortunately 1.19.2 is no longer supported by MCreator... therefore not by me either. If this issue persists in newer versions, let me know and I will reopen this issue.
