### ISSUE TITLE
GeckoLib entities are not compiled in 1.20.1

### ISSUE THREAD

**Issue by MagicalAlexey** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#50]
GeckoLib entities are not compiled in Minecraft Forge 1.20.1. Perhaps this is due to changes in the entity code.
Logs: https://pastebin.com/er5zhmtZ

**Comment by NerdyPuzzle** [comment]
I'll fix it this Friday when I'm out of the military.

**Comment by Dukeasas** [comment]
Any updates on this?

**Comment by mumke** [comment]
Im also having the same problem

**Comment by KlemenDEV** [comment]
I can pinpoint bug to line https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/blob/79e90a2eb817d6302e6417fb9ef18c1cedc111c9/src/main/resources/forge-1.20.1/templates/aentity/livingentity.java.ftl#L870

**Comment by KlemenDEV** [comment]
Some users are also reporting this:

> error: level has private access in Entity this.lastSwing = level.getGameTime();

**Comment by MagicalAlexey** [comment]
@KlemenDEV Are you by any chance unable to support this plugin?

**Comment by KlemenDEV** [comment]
My all available time is spent on MCreator, so the answer is no. But the community is big and there are several developers, so maybe if someone else has time and motivation, they can, but it would be only fair they coordinate this with Nerdy as original project owner

**Comment by drmilk240** [comment]
It's been multiple months with no news on whether this is getting fixed. Is there any sort of way I could temporarily fix the animated entity code?

I don't mind delving into the code a little bit, but the issue seems to be a relatively simple issue with private access stuff, so what should I change in my code to actually get it to build?

(I'm getting the following error:)
`error: level has private access in Entity this.lastSwing = level.getGameTime();`

**Comment by KlemenDEV** [comment]
For this particular case, changing `this.lastSwing = level.getGameTime();` to `this.lastSwing = level().getGameTime();` should do the trick

**Comment by pringlethegoat** [comment]
Any update on this at all? Facing the same Issue unfortunately

**Comment by Fantasia-mod** [comment]
Hello ! Any update on this issue ? Have a good day

**Comment by NerdyPuzzle** [comment]
Probably fully fixed. Will reopen if any of you report more compilation errors here with the latest version.

**Comment by MagicalAlexey** [comment]
I checked. Everything works fine.

**Comment by Uh-huh117** [comment]
Hello! I'm having this problem, even while running the newest version of MCreator. I tried an older version of MCreator too, but it didn't work. Could being on MacOS be the problem?

**Comment by NerdyPuzzle** [comment]
Most compilation issues now stem from broken gradle caches as the majority of bugs that caused that have been fixed.
