### ISSUE TITLE
Attack animation loop 1.19.2/1.19.4/1.20.1

### ISSUE THREAD

**Issue by hampop** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#51]
https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/87606666/a7938899-e203-49bc-a291-42e345525cc0

**Comment by NerdyPuzzle** [comment]
It's because you used the aggression animation and not the attack animation. The aggression animation plays on loop while the mob is angry.

**Comment by hampop** [comment]
> 

![image](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/87606666/f6d2dcf9-73a5-465d-8012-1613d75ce415)

**Comment by hampop** [comment]
so what could it be

**Comment by MagicalAlexey** [comment]
Perhaps you have a loop in the animation

**Comment by NerdyPuzzle** [comment]
Does the issue persist if you put the animation into "play once" mode in blockbench?

**Comment by hampop** [comment]
will test in a bit to see

**Comment by hampop** [comment]
ah it seems to fix it idk why in 2023.1 version of the plugin  it was fine being loop but that is fine for me to fix my animations for 2023.3

**Comment by NerdyPuzzle** [comment]
It's the geckolib mod's new feature, blockbench loop modes take priority over code.

**Comment by hampop** [comment]
ah ok

**Comment by NerdyPuzzle** [comment]
Idk why I kept this issue open but it should be closed.
