### ISSUE TITLE
Item Animations not transitioning Correctly

### ISSUE THREAD

**Issue by Palezam** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#52]
I don't really know how to put it into words but I'll do my best. When a animation of a item finishes. It flashes, and then snaps back to the idle animation. Some of them skip due to to the video compression but the first one you can see the issue.

Mcreator v2023.2
Geckolib v4.8.7
Forge v1.19.2

https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/62035526/77623ed4-75f4-4ae7-b143-e7297ffa5b46

**Comment by NerdyPuzzle** [comment]
Are you using the "only play in first person" option? I think it could be an issue with that. Let me know so I can look into this more.

**Comment by NerdyPuzzle** [comment]
No response from the issue author
