### ISSUE TITLE
Feature Request (Blockbench loop types backport)

### ISSUE THREAD

**Issue by Sherfyy** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#57]
Blockbench loop types (play once, loop, hold onto last frame) don't work in-game for forge 1.19.2
Please, I really need this and probably many users will be also happy if this backport happens.

**Comment by NerdyPuzzle** [comment]
That feature was introduced by the devs of the geckolib mod so I have no control over it.
