### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by TapkuKabaadi** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#6]
[Flinger.zip](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/files/10610591/Flinger.zip)
I am getting a compile error whenever I add a mob. I have seen many tutorials and tried regenerating the code, but it didn't work.
Please help me figure this out.

**Comment by NerdyPuzzle** [comment]
I do not support outdated versions of the plugin.
