### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by Verekenoob** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#61]
Hello, I have an error that doesn't let me place my entity created with geckolib mcreator, I don't know why.

**Comment by pringlethegoat** [comment]
Is this happening in-game ? If so is it Crashing after placing an entity or is the entity respawning / invisible etc

**Comment by Fantasia-mod** [comment]
Same problem but the entity is not spawning and the game crash instantly

**Comment by pringlethegoat** [comment]
Do you have a Crash-log you can post here? It would help with diagnosing the Issue massively since it could be a number of things, thanks

**Comment by NerdyPuzzle** [comment]
Did not provide mcreator version, minecraft version, plugin version, nor the crashlog. Consider this issue invalid unless that is done.

**Comment by MagicalAlexey** [comment]
> Did not provide mcreator version, minecraft version, plugin version, nor the crashlog. Consider this issue invalid unless that is done.

Will there be an upgrade to 2023.4?

**Comment by NerdyPuzzle** [comment]
Closing due to a lack of information provided.
