### ISSUE TITLE
"Rendering Overlay" issue after adding a new entity

### ISSUE THREAD

**Issue by thunderingstatic** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#62]
Hi! My mod, which I've been working on for a while, suddenly no longer will compile correctly (game crashes almost instantly upon opening) because of a "Rendering overlay" issue? If anyone could help me out with this, I'd greatly appreciate it.

I've attached the crashlog from MCreator here:
https://pastebin.com/snrT9wKt

**Comment by EnderPreston** [comment]
I'm having this problem as well. I really hope Nerdy notices this soon.

Here's my latest.log file, by the way. This extra information should be able to help Nerdy fix this issue.
https://pastebin.com/nVGYWDcL

**Comment by NerdyPuzzle** [comment]
Both cases are caused by broken animation files. You'll just have to delete the files from the workspace. The animations are broken when converted from the bedrock format.

**Comment by NerdyPuzzle** [comment]
@thunderingstatic @EnderPreston try my new application [GeckoLib animation fixer](https://www.mediafire.com/file/urrv45s50bioow4/GeckoLib_animation_fixer.exe/file) on your workspaces. It should fix your animation files.

**Comment by EnderPreston** [comment]
Two questions: Where do I put this in my workspace folder, and why does Windows keep saying it's a virus?

**Comment by NerdyPuzzle** [comment]
You open it, select your workspace, and press fix workspace animations. Windows probably thinks it's a virus because it's not signed with a certificate.

**Comment by NerdyPuzzle** [comment]
But really, if I actually wanted to give people viruses, it would have been alot easier to do it with java plugins than by trying to get them to run programs.
