### ISSUE TITLE
geckolib mob compilation error.HELP

### ISSUE THREAD

**Issue by Resum47** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#63]
I have created a mob with geckolib, but when compiling the project comes out this error, there are animations walking, idle, death and attack. Perhaps the problem in a large number of polygons in the model. Please help who has encou

![изображение_2023-11-02_192835570](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/149680803/3f97b760-af52-4299-a28a-d114437b9c2a)
ntered such a problem.

**Comment by NerdyPuzzle** [comment]
This tells me absolutely nothing. At least show the console.

**Comment by Resum47** [comment]
> This tells me absolutely nothing. At least show the console.

in zip archive workspace with error and geckolib 1.20.1 , for familiarization

![изображение_2023-11-03_141850150](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/149680803/832cf068-aa16-4f82-b7d2-360c6578b5c9)

[error bird.zip](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/files/13248512/error.bird.zip)

**Comment by NerdyPuzzle** [comment]
Update to the latest version of the plugin.
