### ISSUE TITLE
fabric 1.20.1 not working

### ISSUE THREAD

**Issue by lilsherm09** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#64]
when trying to make a geckolib fabric 1.20.1 mod with the plugin it will say send this error and when you click regenerate it will just infinitly loop this text prompt
![image](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/116927046/8d3db1a3-28ec-47e3-af2a-3017e4eab657)

**Comment by NerdyPuzzle** [comment]
This version is not yet supported.

**Comment by Abdulhanan535** [comment]
Will you add support for it brother? or can you guide me add it to 1.20.1 Fabric?
