### ISSUE TITLE
Can't tick the attack animation because it causes the compil to crash

### ISSUE THREAD

**Issue by Choupiclou** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#68]
When I'm on my custom entity and I try to give it an attack animation the compil always crashes and I don't know why, if you have any ideas ?

**Comment by NerdyPuzzle** [comment]
the latest version fixes the build error.

**Comment by Choupiclou** [comment]
> the latest version fixes the build error.

Thank you !
