### ISSUE TITLE
cant make a mob type as "creature"

### ISSUE THREAD

**Issue by Releahh** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#69]
I get shown this build log each time i try to set a mob as creature, i have all the right versions together and working, have tried on ther models and vanilla models and yet does not seem to work, any ideas? Most likely a simple error on my side but unsure how to resolve.

Executing Gradle task: build 
Build info: MCreator 2023.3.36712, forge-1.20.1, 64-bit, 8023 MB, Windows 11, JVM 17.0.7, JAVA_HOME: C:\Program Files\Pylo\MCreator\jdk, started on: 2023-11-21-02:21:01 
  
> Task :compileJava FAILED 
[C:\Users\44793\MCreatorWorkspaces\project\src\main\java\net\mcreator\project\entity\OstrichEntity.java:175](file:///C:/Users/44793/MCreatorWorkspaces/project/src/main/java/net/mcreator/project/entity/OstrichEntity.java:175): error: cannot find symbol 
            (entityType, world, reason, pos, random) -> (world.getBlockState(pos.below()).getMaterial() == Material.GRASS && world.getRawBrightness(pos, 0) > 8)); 
                                                                                         ^ 
  symbol:   method getMaterial() 
  location: class BlockState 
[C:\Users\44793\MCreatorWorkspaces\project\src\main\java\net\mcreator\project\entity\OstrichEntity.java:175](file:///C:/Users/44793/MCreatorWorkspaces/project/src/main/java/net/mcreator/project/entity/OstrichEntity.java:175): error: cannot find symbol 
            (entityType, world, reason, pos, random) -> (world.getBlockState(pos.below()).getMaterial() == Material.GRASS && world.getRawBrightness(pos, 0) > 8)); 
                                                                                                                   ^ 
  symbol:   variable GRASS 
  location: class Material 
2 errors 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':compileJava'. 
> Compilation failed; see the compiler error output for details. 
* Try: 
> Run with --stacktrace option to get the stack trace. 
> Run with --info or --debug option to get more log output. 
> Run with --scan to get full insights. 
* Get more help at https://help.gradle.org 
BUILD FAILED in 2s 
1 actionable task: 1 executed 
  
BUILD FAILED 
Task completed in 4 seconds

**Comment by NerdyPuzzle** [comment]
Error in the plugin. I'll fix it very soon.

**Comment by NerdyPuzzle** [comment]
Nevermind. Turns out I fixed this a long time ago. Update your plugin.

**Comment by Releahh** [comment]
As stated, all is up to date and updated correctly as i thought that may have been the issue to begin with so the versions and plugins are all compatible just doesnt seem to work still

**Comment by NerdyPuzzle** [comment]
Are you certain you don't have multiple versions of the plugin in the plugin folder? I looked in the templates in the plugin and the code shown in the error doesn't exist...
