### ISSUE TITLE
Changing procedures break locked gecko entities

### ISSUE THREAD

**Issue by tiltproof69** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#7]
Hey there, I stumbled upon a problem with gecko entities [plugin 4.4, mcr EAP 2023.1.04717, forge 1.19.2 (probably also for 1.18.2)]

When I attach a procedure to an animated entity's trigger in the entity triggers section (like on entity tick update, or any other), lock the entity's code, and change something in the procedure, there occurs an error saying that the entity could not compile with executing the procedure.

Example when changing on entity tick update procedure:
error: method execute in class HoverScooterOnEntityTickUpdateProcedure cannot be applied to given types; 
 HoverScooterOnEntityTickUpdateProcedure.execute(this.level, this.getX(), this.getY(), this.getZ(), this);
 
 
![image](https://user-images.githubusercontent.com/98851333/217228246-f05737f4-08ab-4e0d-80c5-6c17208d58a0.png)

How to recreate:
Make an animated entity, create a procedure, e.g. on entity tick update, and add e.g. "strike lighting at **x** y z". Lock the entity's code, and try to change the procedure to "strike lighting at **x position of event target entity**, y, z"

**Comment by NerdyPuzzle** [comment]
This is not a geckolib error. This is just a case of arguments you require no longer matching the arguments provided.

**Comment by NerdyPuzzle** [comment]
For example, adding an entity to the procedure won't update the entity's code to provide it since its locked.
