### ISSUE TITLE
Geckolib no longer working on 1.18.2

### ISSUE THREAD

**Issue by pploh** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#70]
Hello again! I just downloaded the newest version of the plugin 
[1.18.2 Not Supported.txt](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/files/13444388/1.18.2.Not.Supported.txt)
that had the fix for the mineable tags for all version(plugin version 4.9.1, however now 1.18.2 has suddenly lost support. I'm not sure if this is intentionally or a bug but I have errors consisting of the message (not supported for generator, etc) ever since I updated
<img width="631" alt="image" src="https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/90290799/3e19f4ba-83c5-4d7b-b70b-4c14b6ecbd25">

**Comment by NerdyPuzzle** [comment]
I simply dropped the version as maintaining 4 versions at once is time consuming.
