### ISSUE TITLE
Geckolib armor Boots dont move.

### ISSUE THREAD

**Issue by ScareForceOne** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#73]
In Mcreator version 2023.3 using the plugin v4.9.2 for MC version 1.20.1 animated armors dont move theirs boots while walking , running etc. The rest of the armor moves like normal when the player moves , except from boots. They just remain static. I only have one Geckolib Armor set so it could be a mistake on my part , but since i had that armor in my workspace before i transfered the workspace from 1.19 to 1.20 i suspect it could be a bug.

**Comment by NerdyPuzzle** [comment]
can't reproduce.
