### ISSUE TITLE
Plugin won't fully load

### ISSUE THREAD

**Issue by InkyLilly** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#74]
![image](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/84817623/621d94d4-6d06-4a87-862b-235c89214277)

When I start up MCreator it says it's fully loaded, but then when I do anything it changes to not fully loaded. I'm not sure how to fix this

**Comment by InkyLilly** [comment]
I should specify I'm using MCreator 2023.1. I can not upgrade to a newer version because newer versions don't support 1.18.2

**Comment by NerdyPuzzle** [comment]
Enable java plugins.

**Comment by NerdyPuzzle** [comment]
Does the plugin work? If so this can be ignored.

**Comment by InkyLilly** [comment]
No, the plugin does not work. It's been giving me errors with all the entities.

**Comment by NerdyPuzzle** [comment]
Show me those errors.

**Comment by InkyLilly** [comment]
Sorry for the late response,
![image](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/84817623/bd0b5512-1e4c-4b4a-98d1-d0ba9abdda2d)
These errors are happening for every geckolib entity.

**Comment by NerdyPuzzle** [comment]
Enable the geckolib API in workspace settings.

**Comment by InkyLilly** [comment]
It is enabled already

**Comment by NerdyPuzzle** [comment]
Then disable it and enable it again.

**Comment by InkyLilly** [comment]
It still says the plugin isn't fully loaded, however the errors seem to be gone. Thank you for helping me out!
