### ISSUE TITLE
GECKOLIB MINECRAFT ERROR

### ISSUE THREAD

**Issue by Lukstaberu** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#75]
while using mcreator, in mcreator i made my model and in mcreator is all ok but when i go test in game create this error  testb (testb) has failed to load correctly  java.lang.reflect.InvocationTargetException: null SOMEONE HELP

**Comment by NerdyPuzzle** [comment]
You need to install the geckolib mod if you want to test it outside mcreator.
