### ISSUE TITLE
Particle Keyframe found for MyEntity -> movement, but no keyframe handler registered

### ISSUE THREAD

**Issue by Antosha42** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#76]
I created an Entity in BlockBench that has particles in animation.
Animations work, but the parts themselves don't, although in BlockBench, everything works fine.
my error: Particle Keyframe found for MyEntity -> movement, but no keyframe handler registered

**Comment by NerdyPuzzle** [comment]
Only regular animation keyframes are supported by the plugin at the moment. I'll mark it as a feature request in case I have the time to implement them.

**Comment by Antosha42** [comment]
> Only regular animation keyframes are supported by the plugin at the moment. I'll mark it as a feature request in case I have the time to implement them.

Great, thanks a lot.

**Comment by endcollector** [comment]
I'd love it if other keyframes are added at some point...
