### ISSUE TITLE
Stop entity animation

### ISSUE THREAD

**Issue by saga912** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#77]
I am using GeckoLib to create custom animated entities, and when I use "_stop current procedure triggered animation_" the animation doesn stops. Screenshot is underneath
![screenANIM](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/155690014/836431a2-d028-4b2d-b05c-8c4eeb4f0bd4)
I would appreciate any help on this problem!

**Comment by NerdyPuzzle** [comment]
This was made before looping animations from blockbench worked and was meant to stop animations that only played once.

**Comment by NerdyPuzzle** [comment]
Fixed in 5.2
