### ISSUE TITLE
When ever there is a mob with gekolib or player animator crashes (srry for my english)

### ISSUE THREAD

**Issue by TrestoXD** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#79]
Hi, i was trying to use the plugin in my mod but it dosn't work here is the crash log.

[crash-2024-01-11_11.39.49-client.txt](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/files/13902581/crash-2024-01-11_11.39.49-client.txt)

The crash happends when i spawn the mob making that if i join again the world crashes instantly.

I hope it can be fixed, thank you.

**Comment by NerdyPuzzle** [comment]
This crash is player animator related not geckolib.

**Comment by TrestoXD** [comment]
thanks
