### ISSUE TITLE
Stop Item Animation doesnt works sometimes

### ISSUE THREAD

**Issue by Natn8r** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#8]
https://www.dailymotion.com/video/x8i3a0t
![Desktop Screenshot 2023 02 07 - 21 50 33 41](https://user-images.githubusercontent.com/90978822/217427646-608eaa28-3e1a-4d31-9f5e-376955208369.png)
Above are a few issues I noticed with the item animations. It seems that stopping the animations doesn't seem to work most of the time, even when it's showing that no animation is being played at the time. Also the item animation detection or playing seems to sometimes be a tick or two late as you can see in a few places. Just thought you should know, did I do something wrong? This is version 4.4 by the way on the second 2023.1 snapshot

**Comment by NerdyPuzzle** [comment]
The issue here is that getting animations is only client+-side, and setting animations is both client and server-side which can cause issues. This is due to the system I have in place for syncing animations limiting me to this.

**Comment by Natn8r** [comment]
Ah, ok. So do you think it'll be possible to fix or no? Totally ok if not, you've put in an incredible amount of work for this plugin already.

**Comment by NerdyPuzzle** [comment]
I don't think I could without overcoplicating things. Either way, you don't have to check if no animation is active, since it won't let you override active animations unless you stop them first.
