### ISSUE TITLE
"stop current procedure triggered animation" wont work

### ISSUE THREAD

**Issue by yomai6868** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#80]
even if the animation itself is set to play once, it still plays the animation on loop and this block won't do anything to it either
![image](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/132700376/138b28c5-dba3-4563-ad67-fe619bef3f21)

**Comment by NerdyPuzzle** [comment]
You need to set it to play once in blockbench. I will eventually rework the system to work with looping animations too.

**Comment by NerdyPuzzle** [comment]
Fixed in 5.2
