### ISSUE TITLE
Is it possible to somehow get geckolib on 1.18.2? 

### ISSUE THREAD

**Issue by Qubsonlol** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#81]
I am asking because I NEED mod on 1.18.2 (I am making addon to mod that is only 1.18.2)

**Comment by Qubsonlol** [comment]
Will v4.7.2 work? (I am still talking about 1.18 2)

**Comment by NerdyPuzzle** [comment]
It will work on the Mcreator version it was made for.
