### ISSUE TITLE
Plant element causing build error

### ISSUE THREAD

**Issue by kotishe666** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#83]
Whenever I'm trying to compile the mod, a plant element cause an error, telling me that it cannot register the plant as an item, I guess.
MCreator 2023.4 with the forge 1.19.2 generator(latest version). Can be reproduced.
![image](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/136707176/0d7457e4-20ba-4fef-816c-ce5208c8b04b)
P.S The issue appears only with 1.19.2 generator

**Comment by NerdyPuzzle** [comment]
Seems more like an issue with the generator plugin than the geckolib plugin. Go report this to that author if removing my plugin doesn't change that.

**Comment by Spectrall368** [comment]
> Seems more like an issue with the generator plugin than the geckolib plugin. Go report this to that author if removing my plugin doesn't change that.

it already came to me, and the error was resolved by removing GeckoLib (from what I understand)

**Comment by NerdyPuzzle** [comment]
> > Seems more like an issue with the generator plugin than the geckolib plugin. Go report this to that author if removing my plugin doesn't change that.
> 
> He already come to me, and the error was resolved by removing GeckoLib (from what I understand)

That makes zero sense. What's happening here is that the plant code isn't generating, and geckolib does not touch plants.

**Comment by kotishe666** [comment]
So, will the issue be fixed?

**Comment by kotishe666** [comment]
> > Seems more like an issue with the generator plugin than the geckolib plugin. Go report this to that author if removing my plugin doesn't change that.
> 
> He already come to me, and the error was resolved by removing GeckoLib (from what I understand)

So, will the issue be fixed?

**Comment by NerdyPuzzle** [comment]
Actually this does seem to be my fault upon further inspection, I apologise.
