### ISSUE TITLE
Multiple of Same Custom Entities break animation.

### ISSUE THREAD

**Issue by bazookablue** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#84]
I'm encountering a issue where if I am spawning more than one of the same animated modded entity (seemingly in a certain range of each other), it breaks one, or both of their animations, causing them to stutter and jitter, or not play the animation entirely. It seems to be "fixed" if there is just one of those entities spawned at a time but obviously that isn't really ideal. Thank you for your time in advance.

**Comment by NerdyPuzzle** [comment]
Are you using shaders? Or optifine? Does this happen in a vanilla MCreator environment without other mods?

**Comment by bazookablue** [comment]
No shaders, and no optifine, just the base mccreator and the geckolib plugin to animate the entities. Just checked in a separate mod workspace using just java entities instead of the geo, it doesn't seem to be an issue (they animate as a regular java entity would). The second I introduce the geo model version with the plugin in the new environment it does the stuttering within range of the same animated entities.

**Comment by bazookablue** [comment]
https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/54251811/0ed2048e-0b29-4425-9935-81a6c733fee0

Here's a video demonstrating the issue. 
The first two entities spawned are the standard non-animated java (bird); 
The "biord" entities are the geckolib animated versions. You can see the walk cycle animation stop completely as well as the stutter. I apologize for the quality, had to compress in order to send it over.

**Comment by NerdyPuzzle** [comment]
And which version of the plugin are you using?

**Comment by bazookablue** [comment]
I'm using version 5.3, the most recent

**Comment by NerdyPuzzle** [comment]
Alright I'll check it out this Thursday. Currently unavailable.

**Comment by NerdyPuzzle** [comment]
Would be nice if you sent your blockbench project too so I can reproduce it with the exact circumstances.

**Comment by bazookablue** [comment]
Thanks for taking the time, here's the blockbench file I used in the example:
[ShellbertBlockBench.zip](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/files/14078579/ShellbertBlockBench.zip)

should include the model, textures, and exports. Thanks again

**Comment by NerdyPuzzle** [comment]
couldnt replicate so I'm putting this on hold until something like this comes up
