### ISSUE TITLE
Animated blocks non-functional when made a block-entity. [GeckoLib3.0]

### ISSUE THREAD

**Issue by EliGliBli3** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#9]
Stumbled across an issue with animated blocks in MCreator 2022.3 where once made into a block entity, the user crashes on the initial loading screen with an error stating `One or more entry values did not copy to the correct id.` This error is found following the warning message `Registry minecraft:block_entity_type: Override did not have an associated owner object. Name: modid:registryname Value: net.minecraft.world.level.block.entity.BlockEntityType@4f64d9cb`

Not making the block a block-entity fixes the issue (obviously), and so it seems we are stuck using other solutions. I'm sure there's a fix that I'm overlooking in the blockentity part of the code. Regardless of the solution, I hope that this isn't too much of a bother to fix. Thanks in advance!

Log: 
[crash-2023-02-20_15.35.02-client.txt](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/files/10788023/crash-2023-02-20_15.35.02-client.txt)

**Comment by NerdyPuzzle** [comment]
It is already fixed in the new versions
