### ISSUE TITLE
A layer adding to transparent part of mob

### ISSUE THREAD

**Issue by ThePrimeDev** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#92]
![image](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/81071854/86f75687-071c-4cdf-a6a6-a34a003456be)
This is how my mob looks like, this is how it should:

![image](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/81071854/720418f5-93b0-4c4e-8bb6-3c826351cfc0)

Also, not any of the animations plays. (Version of MCreator 2023.1, MC version 1.18.2)

**Comment by NerdyPuzzle** [comment]
2023.1 and 1.18.2 are no longer supported

**Comment by ThePrimeDev** [comment]
> 2023.1 and 1.18.2 are no longer supported

Then how should I make a mod with animated entities on 1.18.2?

**Comment by NerdyPuzzle** [comment]
🤷

**Comment by ThePrimeDev** [comment]
@NerdyPuzzle This happens on 1.20.1 with latest geckolib plugin too.

**Comment by ThePrimeDev** [comment]
How it looks:
![image](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/81071854/2a89e253-4776-4ebe-94c3-adf5236f46b3)
and

How it should look like: 

![image](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/81071854/e55e6045-af24-49d3-9709-8202f611261f)

**Comment by NerdyPuzzle** [comment]
This just seems like a case of a messed up model.

**Comment by NerdyPuzzle** [comment]
Are you using some weird blockbench plugin like azurelib animation utils? Either way, no model I made had this issue.

**Comment by ThePrimeDev** [comment]
@NerdyPuzzle I found the issue: It was fricked up because a cube, which properties was just weird. I guess just a corrupt bbmodel file. Still doesn't gives explanation why some custom anims won't work
