### ISSUE TITLE
Add older versions

### ISSUE THREAD

**Issue by ElgerElg** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#93]
I think it's a good to add older version of geckolib with support 2022.3, 2022,2 and for Minecraft forge 1.16.5

**Comment by NerdyPuzzle** [comment]
Too much work. No thanks.

**Comment by ElgerElg** [comment]
Lazy...

**Comment by NerdyPuzzle** [comment]
Yeah, sorry for being too lazy to **rewrite the entire plugin** several times 😞
