### ISSUE TITLE
Version 5.4.1 deleting "ModItems.java" init file when regenerating code

### ISSUE THREAD

**Issue by Marianz222** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#94]
Hey Nerdy, I've already talked about this issue in the MCreator website. Basically my workspace is a quite big one, with 6.5k elements on it. When I use the latest version of the plugin (5.4.1 in this case) My "ModItems.java" initialization file failes to be generated when rebuilding the code, and yes it is in fact a Geckolib problem since other plugins work fine, but when I add yours it just doesn't re-generate the Items init file. Hope this helps resolve the issue.

Attached my [.zip workspace](https://www.mediafire.com/file/umj3kclow0un2uf/Alterlands+workspace.zip/file) and some images, thank you!

My gradle log can be found [here](https://pastebin.com/kaAJsGLg).

The first image is pre installing the plugin, second one is with the plugin installed and after regenerating code. The file is gone.

![Alterlands  C__Users_Mariano_MCreatorWorkspaces_alterlands  - MCreator 2023 4 6_3_2024 11_03_27](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/89351293/d9fd4e2d-4529-4c16-bb50-78573cce685e)

![Alterlands  C__Users_Mariano_MCreatorWorkspaces_alterlands  - MCreator 2023 4 6_3_2024 11_03_27](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/89351293/12a0e123-4d55-482b-a650-9ae92879e067)

**Comment by NerdyPuzzle** [comment]
Can you run MCreator with MCreator.bat and send me the logs up until the point where you regenerate the code? MCreator.bat is located In the same place as mcreator.exe

**Comment by NerdyPuzzle** [comment]
Are you sure you deleted any old versions before loading 5.4.1? Also provide a screenshot of the manage plugins tab in preferences along with the logs.

**Comment by Marianz222** [comment]
Yes, i've only used one version of the plugin at a time. One odd thing that happened sometimes is that the plugin says there's an update avaiable, when there's nothing and the window says "Current version: 5.4.1 - New version 5.4.1", not that important imo.
I've just downloaded the newest version, removing first the old one and then dragging the newest, but that sadly didn't fix the issue. Below is the log I got from executing the bat file, it's in .txt because too large to share in pastebin. Thank you again and hope this helps!

[bat file log.txt](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/files/14532557/bat.file.log.txt)

![Alterlands  C__Users_Mariano_MCreatorWorkspaces_alterlands  - MCreator 2023 4 7_3_2024 23_56_48](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/89351293/a6900bf6-1fec-4c14-a09c-027b694a5e22)

![Alterlands  C__Users_Mariano_MCreatorWorkspaces_alterlands  - MCreator 2023 4 7_3_2024 23_56_35](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/89351293/5534ccdf-b724-466a-b807-e070225bf9cb)

**Comment by NerdyPuzzle** [comment]
Thank you for the log, it has helped me find what the issue is and I'll be fixing it.

**Comment by NerdyPuzzle** [comment]
Thank you for the bug report!

**Comment by Marianz222** [comment]
Amazing, thank you so much dude! Happy to contribute in some way, your work is amazingly useful
