### ISSUE TITLE
"play animation named" is a number

### ISSUE THREAD

**Issue by Spoghet99** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#95]
I really don't get what i need to do. If i create a procedure and use "play animation named" from gekolib i can only use numbers. How am i supposed to tell it which animation it needs to do?
![issue](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/161731579/e8548526-469a-44cf-9c0a-98b9df445bf3)

**Comment by NerdyPuzzle** [comment]
you name the animation as a number when making it in blockbench.
