### ISSUE TITLE
Geckolib Failed to Load

### ISSUE THREAD

**Issue by unschoolingwithfin** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#97]
I need help getting geckolib 5.4.3 to load on mcreator 2023.4. I'm on a mac studio 2022, M1 Max apple chip (silicone), running MacOS Ventura 14.4

I installed the zipped plugin in the .mcreator/plugins folder. 

When I load mcreator, I get this error:

The following plugins failed to load: Nerdys_Geckolib_Plugin

When I click more info, I get this:

Some plugins failed to load: Nerdys_Geckolib_Plugin - reason: IO error: Cannot assign field "builtin" because "plugin" is null.

<img width="647" alt="Screenshot 2024-03-17 at 10 41 34 AM" src="https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/163748681/36686511-e7cf-40fd-a6f8-f4738972ddc3">

Any suggestions on how I can get this to work?

Ty!

**Comment by NerdyPuzzle** [comment]
Somehow you managed to mess up the plugin file. You should load the zip from the plugin page and it will work fine.
