### ISSUE TITLE
alternating animations

### ISSUE THREAD

**Issue by mynameares** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#98]
Hello! how do I use two animations of the same action? I want the character to alternate attack animations. How do I achieve this?

**Comment by NerdyPuzzle** [comment]
You use procedures instead of built in animations. But this is not the place to ask for tutorials, this is an issue tracker.

**Comment by mynameares** [comment]
> You use procedures instead of built in animations. But this is not the place to ask for tutorials, this is an issue tracker.

Excuse me, where else can I ask my questions about the procedures?
