### ISSUE TITLE
Problem with block mining speed

### ISSUE THREAD

**Issue by KnightKing777** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#99]
I have already written about this problem in the comments, but let's start from the beginning. All my newly created blocks in a specific workspace stop destroying properly, they destroy very slowly, repairing gradle, new gradle, rebuilding the code does nothing. I tried copying the workspace to another project, it didn't change anything, removing the geckolib plugin didn't change either, I know that there was once the same error in geckolib. I have the latest version of geckolib 5.4.3. I deleted the old version of geckolib from the plugins folder and added a new one. It didn't change anything. I would ask for help.

**Comment by NerdyPuzzle** [comment]
If removing geckolib doesn't change anything then geckolib isn't causing the issue.

**Comment by KnightKing777** [comment]
> If removing geckolib doesn't change anything then geckolib isn't causing the issue.

I already know why I have such problems, probably (I'm 99% sure) that it's the plugin's fault, to fix the broken block you need to remove the GeckoLib plugin from the plugins folder, run workspace and reload gradle, you can then load the plugin and the block will work, but newly added blocks still have problems with mining speed, to fix them I have to do the above-mentioned action
